type ClassValue = false | null | string | undefined;

export function cx(...values: ClassValue[]) {
  return values.filter(Boolean).join(" ");
}

const focusRing = "focus-visible:[outline:3px_solid_var(--color-focus)] focus-visible:outline-offset-4";
const displayFont = "[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]";
const bodyFont = "[font-family:'Atkinson_Hyperlegible_Next_Variable','Atkinson_Hyperlegible_Next',ui-sans-serif,system-ui,sans-serif]";
const container = "w-[var(--container)] mx-auto";
const fullBleed1180 = "w-full mx-0 px-[max(1rem,calc((100vw-1180px)/2))]";
const fullBleed1320 = "w-full mx-0 px-[max(1.25rem,calc((100vw-1320px)/2))]";
const darkGridBackground = "[background:linear-gradient(90deg,color-mix(in_oklch,var(--color-sky),transparent_90%)_1px,transparent_1px),linear-gradient(0deg,color-mix(in_oklch,var(--color-mint),transparent_91%)_1px,transparent_1px),var(--color-dark)] bg-[length:4.5rem_4.5rem,4.5rem_4.5rem,auto]";
const lightGridBackground = "[background:radial-gradient(circle_at_14%_24%,color-mix(in_oklch,var(--color-aqua-soft),transparent_20%),transparent_24rem),radial-gradient(circle_at_82%_18%,color-mix(in_oklch,var(--color-lilac),transparent_28%),transparent_26rem),linear-gradient(90deg,color-mix(in_oklch,var(--color-ink),transparent_95%)_1px,transparent_1px),linear-gradient(0deg,color-mix(in_oklch,var(--color-ink),transparent_96%)_1px,transparent_1px),var(--color-bg)] bg-[length:auto,auto,4.5rem_4.5rem,4.5rem_4.5rem,auto]";

export const themeVars = cx(
  "[color-scheme:light]",
  "[--color-bg:oklch(0.992_0.012_94)]",
  "[--color-surface:oklch(0.973_0.016_105)]",
  "[--color-ink:oklch(0.19_0.018_252)]",
  "[--color-muted:oklch(0.43_0.026_238)]",
  "[--color-rule:oklch(0.885_0.014_108)]",
  "[--color-primary:oklch(0.78_0.13_78)]",
  "[--color-primary-ink:oklch(0.15_0.015_80)]",
  "[--color-mint:oklch(0.82_0.105_162)]",
  "[--color-mint-ink:oklch(0.18_0.04_165)]",
  "[--color-sky:oklch(0.82_0.085_230)]",
  "[--color-sky-ink:oklch(0.18_0.04_245)]",
  "[--color-coral:oklch(0.78_0.13_35)]",
  "[--color-blush:oklch(0.9_0.055_28)]",
  "[--color-lilac:oklch(0.89_0.05_302)]",
  "[--color-aqua-soft:oklch(0.91_0.06_185)]",
  "[--color-dark:oklch(0.09_0.006_260)]",
  "[--color-dark-surface:oklch(0.14_0.01_260)]",
  "[--color-dark-panel:oklch(0.115_0.012_260)]",
  "[--color-dark-ink:oklch(0.96_0.01_160)]",
  "[--color-dark-muted:oklch(0.76_0.035_180)]",
  "[--color-dark-rule:color-mix(in_oklch,var(--color-dark-ink),transparent_78%)]",
  "[--color-dark-honey:oklch(0.78_0.13_78)]",
  "[--color-dark-mint-panel:color-mix(in_oklch,var(--color-mint),var(--color-dark)_86%)]",
  "[--color-honey-soft:oklch(0.92_0.08_82)]",
  "[--color-focus:oklch(0.48_0.16_255)]",
  "[--text-caption:0.8125rem]",
  "[--text-small:0.875rem]",
  "[--text-body:1rem]",
  "[--text-lead:1.25rem]",
  "[--text-h3:1.75rem]",
  "[--text-h2:3.25rem]",
  "[--text-hero:4.25rem]",
  "[--text-home-hero:4.05rem]",
  "[--leading-caption:1.35]",
  "[--leading-body:1.62]",
  "[--leading-lead:1.45]",
  "[--leading-heading:1.04]",
  "[--leading-dark-body:1.7]",
  "[--container:min(100%_-_clamp(1rem,4vw,3rem),1180px)]",
  "[--container-wide:min(100%_-_clamp(1rem,4vw,3rem),1440px)]",
  "[--shadow-soft:0_1.35rem_4rem_color-mix(in_oklch,var(--color-sky-ink),transparent_88%)]",
  "[--shadow-lifted:0_1rem_2.6rem_color-mix(in_oklch,var(--color-ink),transparent_90%)]",
  "max-[860px]:[--text-h2:2.65rem]",
  "max-[860px]:[--text-hero:3.35rem]",
  "max-[860px]:[--text-home-hero:3.35rem]",
  "max-[560px]:[--container:min(100%_-_1.2rem,1180px)]",
  "max-[560px]:[--text-lead:1.125rem]",
  "max-[560px]:[--text-h3:1.5rem]",
  "max-[560px]:[--text-h2:2.1rem]",
  "max-[560px]:[--text-hero:2.65rem]",
  "max-[560px]:[--text-home-hero:2.65rem]",
);

export const bodyClass = cx(
  themeVars,
  bodyFont,
  "m-0 overflow-x-hidden bg-[var(--color-bg)] text-[color:var(--color-ink)] text-[length:var(--text-body)] leading-[var(--leading-body)] [overflow-wrap:break-word] [text-rendering:optimizeLegibility]",
);

export const ui = {
  siteShell: cx(
    "min-h-screen overflow-x-hidden",
    "[&_main]:min-w-0 [&_section]:min-w-0 [&_figure]:min-w-0",
    "[&_a]:text-inherit",
    "[&_h1]:m-0 [&_h1]:max-w-[15ch] [&_h1]:text-[length:var(--text-hero)] [&_h1]:font-[760] [&_h1]:leading-[var(--leading-heading)] [&_h1]:tracking-normal [&_h1]:[overflow-wrap:normal] [&_h1]:[text-wrap:balance]",
    "[&_h1]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]",
    "[&_h2]:m-0 [&_h2]:max-w-[13ch] [&_h2]:text-[length:var(--text-h2)] [&_h2]:font-[680] [&_h2]:leading-[var(--leading-heading)] [&_h2]:tracking-normal [&_h2]:[overflow-wrap:normal] [&_h2]:[text-wrap:balance]",
    "[&_h2]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]",
    "[&_h3]:m-0 [&_h3]:leading-[var(--leading-heading)] [&_h3]:tracking-normal [&_h3]:[overflow-wrap:normal] [&_h3]:[text-wrap:balance]",
    "[&_h3]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]",
  ),
  skipLink: cx(
    focusRing,
    displayFont,
    "fixed top-4 left-4 z-10 -translate-y-[150%] border border-[var(--color-dark)] bg-[var(--color-bg)] px-[0.9rem] py-[0.7rem] font-[520] focus:translate-y-0 focus-visible:translate-y-0",
  ),
  siteHeader: "sticky top-0 z-[5] border-b border-[color-mix(in_oklch,var(--color-rule),transparent_25%)] bg-[color-mix(in_oklch,var(--color-bg),transparent_8%)] text-[color:var(--color-ink)] backdrop-blur-[14px]",
  siteNav: cx(container, "flex items-center justify-between gap-4 py-4 max-[860px]:flex-row max-[860px]:flex-wrap max-[560px]:flex-nowrap"),
  brandLockup: "flex min-w-max items-center gap-3 no-underline max-[560px]:min-w-11",
  brandSymbol: "inline-grid aspect-square w-[2.6rem] place-items-center overflow-hidden border border-[color-mix(in_oklch,var(--color-rule),transparent_30%)] bg-[color-mix(in_oklch,var(--color-sky),var(--color-bg)_88%)]",
  brandMark: "block aspect-square w-[2.6rem] object-contain [transform:scale(1.72)_translateY(-8%)]",
  brandText: cx(displayFont, "grid font-[680] leading-[1.1] max-[560px]:hidden [&_small]:text-[color:var(--color-muted)] [&_small]:text-[length:var(--text-caption)] [&_small]:font-[520]"),
  navLinks: cx(
    displayFont,
    "flex flex-wrap items-center justify-end gap-[clamp(0.6rem,1.5vw,1.35rem)] text-[length:var(--text-small)] font-[580] max-[860px]:flex-[1_1_22rem] max-[860px]:overflow-x-auto max-[860px]:whitespace-nowrap max-[860px]:[scrollbar-width:none] max-[860px]:[&::-webkit-scrollbar]:hidden max-[560px]:flex-[1_1_auto] max-[560px]:flex-nowrap max-[560px]:justify-start max-[560px]:gap-[0.85rem]",
    "[&_a]:inline-flex [&_a]:min-h-11 [&_a]:min-w-11 [&_a]:items-center [&_a]:decoration-1 [&_a]:underline-offset-[0.25em] max-[560px]:[&_a]:min-w-0",
  ),
  siteFooter: cx(container, "grid grid-cols-[minmax(0,1fr)_auto] gap-8 border-t border-[var(--color-dark)] py-8 max-[860px]:grid-cols-1 [&_p]:m-0 [&_p]:max-w-[64ch] [&_p]:text-[color:var(--color-muted)]"),
  footerKicker: cx(displayFont, "mb-[0.3rem] !text-[color:var(--color-ink)] font-bold"),
  footerLinks: cx(displayFont, "flex flex-wrap justify-end gap-4 text-[length:var(--text-small)] font-[620] max-[860px]:justify-start [&_a]:inline-flex [&_a]:min-h-11 [&_a]:min-w-11 [&_a]:items-center [&_a]:decoration-1 [&_a]:underline-offset-[0.25em] max-[560px]:[&_a]:min-w-0"),
  footerDashboardLink: "inline-flex min-h-11 items-center border border-[var(--color-dark)] bg-[var(--color-mint)] px-4 text-[color:var(--color-mint-ink)] no-underline",
  copyright: "col-span-full text-[length:var(--text-caption)] [font-variant-numeric:tabular-nums]",
  sectionContainer: container,
  fullBleed1180,
  fullBleed1320,
  signalLine: cx(displayFont, "m-0 mb-5 text-[color:var(--color-muted)] text-[length:var(--text-small)] font-[680]"),
  heroLead: "mt-[1.6rem] mb-0 max-w-[60ch] text-[color:var(--color-muted)] text-[length:var(--text-lead)] leading-[var(--leading-lead)] [text-wrap:pretty] max-[560px]:mt-[1.05rem]",
  heroActions: "mt-8 flex flex-wrap items-center gap-[0.85rem] max-[560px]:mt-[1.3rem] max-[560px]:gap-[0.65rem]",
  button: cx(focusRing, displayFont, "inline-flex min-h-12 items-center justify-center border border-[var(--color-dark)] px-4 py-[0.85rem] text-[length:var(--text-small)] font-[680] no-underline disabled:opacity-70"),
  buttonPrimary: "bg-[var(--color-primary)] text-[color:var(--color-primary-ink)]",
  buttonSecondary: "bg-[var(--color-bg)]",
  buttonSecondaryOnLightHero: "border-[color-mix(in_oklch,var(--color-ink),transparent_76%)] bg-[color-mix(in_oklch,var(--color-bg),transparent_14%)] text-[color:var(--color-ink)]",
  buttonSecondaryOnDark: "border-[var(--color-dark-rule)] bg-transparent text-[color:var(--color-dark-ink)]",
  buttonWhatsapp: "border-[var(--color-mint-ink)] bg-[var(--color-mint)] text-[color:var(--color-mint-ink)]",
  sectionHeading: "mb-[clamp(2rem,5vw,4rem)] grid gap-[0.2rem]",
  sectionIntro: "mt-4 mb-0 max-w-[62ch] text-[color:var(--color-muted)] text-[length:var(--text-lead)] leading-[var(--leading-lead)] [text-wrap:pretty]",
  homeProofHero: cx(
    "grid w-full grid-cols-[minmax(22rem,0.42fr)_minmax(36rem,0.58fr)] items-center gap-[clamp(2rem,4.8vw,5.5rem)] min-h-[min(720px,calc(100svh-77px))] border-b-0 px-[max(1.25rem,calc((100vw-1320px)/2))] py-[clamp(3rem,5.2vw,5.4rem)] pb-[clamp(1.25rem,2.6vw,2.4rem)] text-[color:var(--color-ink)] shadow-[inset_0_-1px_color-mix(in_oklch,var(--color-rule),transparent_18%)] max-[860px]:grid-cols-1 max-[860px]:gap-[clamp(1.5rem,5vw,2.5rem)] max-[860px]:min-h-0 max-[860px]:py-[clamp(2rem,7vw,4rem)] max-[560px]:max-w-[100vw] max-[560px]:overflow-hidden max-[560px]:px-4",
    "[background:radial-gradient(circle_at_18%_20%,color-mix(in_oklch,var(--color-blush),transparent_18%),transparent_24rem),radial-gradient(circle_at_78%_12%,color-mix(in_oklch,var(--color-sky),transparent_26%),transparent_27rem),radial-gradient(circle_at_68%_76%,color-mix(in_oklch,var(--color-mint),transparent_28%),transparent_30rem),linear-gradient(90deg,color-mix(in_oklch,var(--color-ink),transparent_94%)_1px,transparent_1px),linear-gradient(0deg,color-mix(in_oklch,var(--color-ink),transparent_96%)_1px,transparent_1px),var(--color-bg)] bg-[length:auto,auto,auto,4.5rem_4.5rem,4.5rem_4.5rem,auto]",
  ),
  homeHeroCopy: "relative z-[2] max-w-[40rem] py-[clamp(0.6rem,3vw,2rem)] pr-0 max-[860px]:py-0 max-[560px]:w-full max-[560px]:max-w-[calc(100vw-2rem)]",
  homeSignalLine: "!text-[color:var(--color-coral)]",
  homeHeadline: "[&>span]:block max-w-[12.6ch] text-[length:var(--text-home-hero)] tracking-normal max-[560px]:max-w-[11.5ch] max-[560px]:text-[length:var(--text-hero)]",
  homeHeroLead: "max-w-[51ch] text-[color:var(--color-muted)] [overflow-wrap:break-word] max-[560px]:w-full max-[560px]:max-w-[calc(100vw-2rem)]",
  proofBoard: "relative m-0 min-h-[clamp(29rem,43vw,37rem)] overflow-hidden max-[860px]:min-h-[clamp(24rem,72vw,34rem)] max-[560px]:max-w-[calc(100vw-2rem)] max-[560px]:min-h-80",
  homeProofBoard: cx(
    "isolate self-center justify-self-end w-[min(100%,56rem)] min-h-[clamp(24rem,34vw,32rem)] aspect-[16/10] rounded-lg border border-[color-mix(in_oklch,var(--color-mint),var(--color-rule)_44%)] bg-[linear-gradient(145deg,color-mix(in_oklch,var(--color-bg),transparent_3%),color-mix(in_oklch,var(--color-sky),var(--color-bg)_78%))] shadow-[var(--shadow-soft)] max-[860px]:min-h-0 max-[560px]:max-w-full max-[560px]:aspect-[1/1.08]",
    "after:absolute after:inset-0 after:z-[2] after:pointer-events-none after:[background:linear-gradient(90deg,color-mix(in_oklch,var(--color-bg),transparent_10%),transparent_44%),linear-gradient(180deg,transparent_56%,color-mix(in_oklch,var(--color-bg),transparent_18%))]",
  ),
  heroArtifactAsset: "absolute inset-0 z-[1] h-full w-full object-cover object-center opacity-[0.42] [filter:saturate(0.96)_contrast(0.94)]",
  heroProofShots: "pointer-events-none absolute inset-[clamp(1rem,2vw,1.6rem)] z-[3] grid grid-cols-[minmax(0,1.08fr)_minmax(0,0.82fr)] grid-rows-2 gap-[clamp(0.7rem,1.3vw,1rem)] max-[560px]:inset-3 max-[560px]:grid-cols-1 max-[560px]:grid-rows-1",
  heroProofFrame: "h-full min-h-0 w-full overflow-hidden rounded-md border border-[color-mix(in_oklch,var(--color-rule),var(--color-ink)_8%)] bg-[var(--color-bg)] shadow-[var(--shadow-lifted)] first:row-span-2 max-[560px]:first:row-auto max-[560px]:[&:nth-child(2)]:hidden max-[560px]:[&:nth-child(3)]:hidden",
  proofImage: "block h-full w-full object-cover object-[center_30%] [filter:saturate(1.04)_contrast(1.03)]",
  proofBoardCaption: cx("absolute top-4 left-4 z-[4] max-w-[min(24rem,calc(100%-2rem))] overflow-hidden rounded-md border border-[color-mix(in_oklch,var(--color-rule),var(--color-mint)_22%)] bg-[color-mix(in_oklch,var(--color-bg),transparent_8%)] px-[0.95rem] py-[0.85rem] shadow-[var(--shadow-lifted)] backdrop-blur-[18px] max-[560px]:hidden", "[&_span]:block [&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-caption)] [&_span]:font-[680] [&_span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_strong]:mt-[0.35rem] [&_strong]:block [&_strong]:text-base [&_strong]:leading-[1.14] [&_strong]:[text-wrap:balance] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_p]:mt-[0.45rem] [&_p]:mb-0 [&_p]:text-[color:var(--color-muted)] [&_p]:text-[length:var(--text-caption)] [&_p]:leading-[var(--leading-caption)] [&_p]:[text-wrap:pretty]"),
  heroProofRibbon: "absolute inset-x-4 bottom-4 z-[3] grid grid-cols-3 overflow-hidden rounded-md border border-[color-mix(in_oklch,var(--color-rule),transparent_18%)] bg-[color-mix(in_oklch,var(--color-bg),transparent_12%)] backdrop-blur-[18px] max-[560px]:inset-x-3 max-[560px]:bottom-3",
  heroProofRibbonItem: cx("grid min-w-0 gap-[0.2rem] border-r border-[color-mix(in_oklch,var(--color-rule),transparent_20%)] px-[0.9rem] py-[0.8rem] text-[color:var(--color-ink)] no-underline last:border-r-0 [&_span]:overflow-hidden [&_span]:text-ellipsis [&_span]:whitespace-nowrap [&_strong]:overflow-hidden [&_strong]:text-ellipsis [&_strong]:whitespace-nowrap", "[&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-caption)] [&_span]:font-[680] [&_span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_strong]:text-[length:var(--text-small)] [&_strong]:font-[760] [&_strong]:leading-[1.1] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]"),
  selectedOutcomes: "w-full px-[max(1rem,calc((100vw-1180px)/2))] py-[clamp(3rem,7vw,6.5rem)]",
  outcomeLedger: "grid border-t border-[var(--color-dark)]",
  outcomeRow: "group grid min-h-[12.25rem] grid-cols-[3rem_minmax(16rem,0.34fr)_minmax(15rem,0.28fr)_minmax(12rem,0.24fr)_2.5rem] items-center gap-[clamp(1rem,2.4vw,2.25rem)] border-b border-[var(--color-rule)] text-inherit no-underline max-[860px]:grid-cols-1 max-[860px]:items-start max-[860px]:gap-[0.6rem] max-[860px]:py-6",
  outcomeIndex: cx(displayFont, "text-[color:var(--color-mint-ink)] text-[length:var(--text-lead)] font-[680] [font-variant-numeric:tabular-nums]"),
  outcomeShot: "m-0 aspect-[1.78] overflow-hidden border border-[var(--color-rule)] bg-[var(--color-surface)] max-[860px]:max-w-[32rem]",
  evidenceFallback: cx(displayFont, "grid w-full place-items-center border border-[var(--color-rule)] bg-[color-mix(in_oklch,var(--color-surface),var(--color-mint)_9%)] text-center text-[color:var(--color-muted)] text-[length:var(--text-caption)] font-[680] max-[860px]:max-w-[32rem]"),
  outcomeSummary: "grid gap-[0.35rem]",
  eyebrow: cx(displayFont, "text-[color:var(--color-muted)] text-[length:var(--text-small)] font-[680]"),
  outcomeTitle: cx(displayFont, "text-[1.7rem] leading-[1.1] tracking-normal"),
  bodyMutedPretty: "m-0 text-[color:var(--color-muted)] leading-[1.55] [text-wrap:pretty]",
  outcomeArrow: "text-right text-[2rem] leading-none text-[color:var(--color-mint-ink)] transition-transform duration-[180ms] ease-out group-hover:translate-x-1 motion-reduce:transition-none max-[860px]:text-left",
  architectureStage: cx("grid w-full grid-cols-[minmax(0,0.78fr)_minmax(24rem,1.22fr)] gap-[clamp(2rem,6vw,6rem)] border-y border-[var(--color-rule)] px-[max(1rem,calc((100vw-1180px)/2))] py-[clamp(3.5rem,8vw,7rem)] my-[clamp(1rem,4vw,3rem)] text-[color:var(--color-ink)] max-[860px]:grid-cols-1", "[background:radial-gradient(circle_at_20%_20%,color-mix(in_oklch,var(--color-mint),transparent_32%),transparent_24rem),radial-gradient(circle_at_86%_14%,color-mix(in_oklch,var(--color-blush),transparent_34%),transparent_26rem),linear-gradient(90deg,color-mix(in_oklch,var(--color-ink),transparent_95%)_1px,transparent_1px),linear-gradient(0deg,color-mix(in_oklch,var(--color-ink),transparent_96%)_1px,transparent_1px),var(--color-surface)] bg-[length:auto,auto,4.25rem_4.25rem,4.25rem_4.25rem,auto]"),
  architectureLead: "mt-5 mb-0 max-w-[62ch] text-[color:var(--color-muted)] text-[length:var(--text-lead)] leading-[var(--leading-lead)] [text-wrap:pretty]",
  architectureProofStack: "grid gap-4",
  framedImage: "m-0 overflow-hidden border border-[color-mix(in_oklch,var(--color-rule),var(--color-ink)_8%)] bg-[var(--color-bg)] shadow-[var(--shadow-lifted)]",
  architectureTrack: "grid content-center border-t border-[color-mix(in_oklch,var(--color-rule),transparent_16%)]",
  architectureStep: "grid grid-cols-[minmax(8rem,0.34fr)_minmax(0,1fr)] gap-4 border-b border-[color-mix(in_oklch,var(--color-rule),transparent_16%)] py-5 max-[860px]:grid-cols-1 [&_span]:text-[color:var(--color-coral)] [&_span]:text-[length:var(--text-small)] [&_span]:font-[680] [&_span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif] [&_p]:m-0 [&_p]:text-[color:var(--color-muted)] [&_p]:leading-[var(--leading-body)]",
  practiceSection: cx(container, "py-[clamp(3rem,7vw,6.5rem)]"),
  practiceHeading: "mb-[clamp(1.25rem,3vw,2rem)] grid gap-[0.2rem]",
  practiceList: "grid border-t border-[var(--color-dark)]",
  practiceItem: "grid grid-cols-[minmax(10rem,0.28fr)_minmax(0,1fr)] gap-5 border-b border-[var(--color-rule)] py-[1.35rem] max-[860px]:grid-cols-1 [&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-small)] [&_span]:font-[680] [&_span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif] [&_p]:m-0 [&_p]:max-w-[72ch] [&_p]:text-[color:var(--color-muted)]",
  contactBand: cx("grid grid-cols-[minmax(0,1fr)_auto] items-end gap-8 border-y border-[var(--color-rule)] py-[clamp(2.4rem,6vw,5rem)] text-[color:var(--color-ink)] max-[860px]:grid-cols-1 [&_p]:mt-5 [&_p]:mb-0 [&_p]:max-w-[62ch] [&_p]:text-[color:var(--color-muted)] [&_p]:text-[length:var(--text-lead)] [&_p]:leading-[var(--leading-lead)] [&_p]:[text-wrap:pretty]", fullBleed1180, "bg-[linear-gradient(90deg,color-mix(in_oklch,var(--color-primary),var(--color-bg)_76%),color-mix(in_oklch,var(--color-mint),var(--color-bg)_78%))]"),
  contactActions: "flex flex-wrap justify-end gap-[0.8rem] max-[860px]:justify-start",
  contactFormSection: cx("grid grid-cols-[minmax(20rem,0.44fr)_minmax(24rem,0.56fr)] items-start gap-[clamp(2rem,6vw,5rem)] py-[clamp(3.5rem,7vw,7rem)] text-[color:var(--color-dark-ink)] max-[860px]:grid-cols-1", fullBleed1180, darkGridBackground),
  contactFormCopy: "sticky top-28 grid content-start gap-0 self-start max-[860px]:static",
  contactDirectActions: "mt-8 flex flex-wrap items-center gap-[0.85rem]",
  contactArchitectureCard: "mt-[clamp(2rem,5vw,3rem)] mb-0 overflow-hidden border border-[var(--color-dark-rule)] bg-[var(--color-dark-panel)]",
  contactForm: "grid gap-4 border border-[var(--color-dark)] bg-[var(--color-bg)] p-[clamp(1rem,2.5vw,1.6rem)] text-[color:var(--color-ink)]",
  contactFormHeading: "mb-2 grid gap-3 [&_h2]:max-w-[16ch] [&_h2]:text-[length:var(--text-h3)] [&_p]:m-0 [&_p]:text-[color:var(--color-muted)] [&_p]:leading-[1.55]",
  fieldGrid: "grid grid-cols-2 gap-4 max-[860px]:grid-cols-1",
  fieldLabel: cx("grid gap-[0.45rem] m-0", "[&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-small)] [&_span]:font-[680] [&_span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_input]:focus-visible:[outline:3px_solid_var(--color-focus)] [&_input]:focus-visible:outline-offset-4 [&_select]:focus-visible:[outline:3px_solid_var(--color-focus)] [&_select]:focus-visible:outline-offset-4 [&_textarea]:focus-visible:[outline:3px_solid_var(--color-focus)] [&_textarea]:focus-visible:outline-offset-4", "[&_input]:w-full [&_input]:border [&_input]:border-[var(--color-rule)] [&_input]:bg-[var(--color-bg)] [&_input]:px-[0.95rem] [&_input]:py-[0.85rem] [&_input]:text-[color:var(--color-ink)] [&_input]:font-[inherit] [&_input]:leading-[var(--leading-body)]", "[&_select]:w-full [&_select]:border [&_select]:border-[var(--color-rule)] [&_select]:bg-[var(--color-bg)] [&_select]:px-[0.95rem] [&_select]:py-[0.85rem] [&_select]:text-[color:var(--color-ink)] [&_select]:font-[inherit] [&_select]:leading-[var(--leading-body)]", "[&_textarea]:min-h-40 [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:border [&_textarea]:border-[var(--color-rule)] [&_textarea]:bg-[var(--color-bg)] [&_textarea]:px-[0.95rem] [&_textarea]:py-[0.85rem] [&_textarea]:text-[color:var(--color-ink)] [&_textarea]:font-[inherit] [&_textarea]:leading-[var(--leading-body)]"),
  contactChoice: cx("grid gap-[0.45rem] m-0 border border-[var(--color-rule)] px-[0.95rem] py-[0.85rem]", "[&_legend]:text-[color:var(--color-muted)] [&_legend]:text-[length:var(--text-small)] [&_legend]:font-[680] [&_legend]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_label]:flex [&_label]:min-h-11 [&_label]:items-center [&_label]:gap-[0.6rem]", "[&_input]:flex-none", "[&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-small)] [&_span]:font-[680] [&_span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]"),
  consentRow: cx("flex min-h-11 items-center gap-[0.6rem] text-[color:var(--color-muted)] text-[length:var(--text-small)] font-[680]", displayFont, "[&_input]:flex-none"),
  contactHoneypot: "absolute size-px overflow-hidden [clip-path:inset(50%)] whitespace-nowrap",
  contactSubmitRow: "mt-8 flex flex-wrap items-center gap-[0.85rem] [&_p]:m-0 [&_p]:text-[color:var(--color-muted)] [&_p]:leading-[1.55] [&_a]:inline-flex [&_a]:min-h-11 [&_a]:items-center",
  contactStatus: cx(displayFont, "m-0 empty:hidden [&:not(:empty)]:border [&:not(:empty)]:border-[var(--color-rule)] [&:not(:empty)]:px-[0.95rem] [&:not(:empty)]:py-[0.85rem] [&:not(:empty)]:text-[length:var(--text-small)] [&:not(:empty)]:font-[520] data-[state=success]:border-[color-mix(in_oklch,var(--color-mint)_55%,var(--color-rule))] data-[state=success]:bg-[color-mix(in_oklch,var(--color-mint)_18%,var(--color-bg))] data-[state=success]:text-[color:var(--color-mint-ink)] data-[state=warning]:border-[color-mix(in_oklch,var(--color-primary)_55%,var(--color-rule))] data-[state=warning]:bg-[color-mix(in_oklch,var(--color-primary)_16%,var(--color-bg))] data-[state=warning]:text-[color:var(--color-primary-ink)] data-[state=error]:border-[color-mix(in_oklch,var(--color-coral)_60%,var(--color-rule))] data-[state=error]:bg-[color-mix(in_oklch,var(--color-coral)_12%,var(--color-bg))] data-[state=error]:text-[color:var(--color-ink)]"),
  architecturePageHero: cx("grid grid-cols-[minmax(0,0.88fr)_minmax(26rem,1.12fr)] items-end gap-[clamp(2rem,6vw,6rem)] min-h-[min(700px,calc(100svh-78px))] border-b border-[var(--color-dark-rule)] py-[clamp(4rem,9vw,7rem)] pb-[clamp(3rem,6vw,5.5rem)] text-[color:var(--color-dark-ink)] max-[860px]:grid-cols-1 max-[860px]:min-h-0", fullBleed1180, darkGridBackground),
  architecturePageCopy: "max-w-[66rem] [&_h1]:max-w-[11ch]",
  architectureHeroAside: "grid gap-4",
  darkPanelFigure: "m-0 overflow-hidden border border-[var(--color-dark-rule)] bg-[var(--color-dark-panel)]",
  sourceIndex: cx("grid gap-4 border-y border-[var(--color-dark)] py-[1.1rem]", "[&_>strong]:text-[length:var(--text-h3)] [&_>strong]:leading-[1.1] [&_>strong]:tracking-normal [&_>strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]"),
  sourceIndexDark: "border-y-[var(--color-dark-rule)]",
  sourceLinks: cx("flex flex-wrap gap-[0.55rem]", "[&_a]:inline-flex [&_a]:min-h-11 [&_a]:items-center [&_a]:border [&_a]:border-[var(--color-rule)] [&_a]:bg-[var(--color-bg)] [&_a]:px-3 [&_a]:py-[0.55rem] [&_a]:text-inherit [&_a]:text-[length:var(--text-small)] [&_a]:font-[680] [&_a]:no-underline [&_a]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]"),
  sourceLinksDark: "[&_a]:border-[var(--color-dark-rule)] [&_a]:bg-[var(--color-dark-mint-panel)] [&_a]:text-[color:var(--color-dark-ink)]",
  sourceLinksInline: "mt-4",
  architectureMap: cx(container, "py-[clamp(2rem,5vw,4.5rem)]"),
  rowList: "grid border-t border-[var(--color-dark)]",
  architectureRow: "grid grid-cols-[minmax(12rem,0.34fr)_minmax(0,1fr)] gap-[clamp(1rem,3vw,3rem)] border-b border-[var(--color-rule)] py-[1.6rem] max-[860px]:grid-cols-1 [&_h3]:text-[length:var(--text-h3)] [&_p]:m-0 [&_p]:max-w-[78ch] [&_p]:text-[color:var(--color-muted)] [&_p]:[text-wrap:pretty]",
  boundaryNote: cx(container, "my-[clamp(1rem,4vw,3rem)] mb-[clamp(4rem,8vw,7rem)] border-y border-[var(--color-dark)] py-[clamp(1.5rem,4vw,3rem)] [&_p]:m-0 [&_p]:max-w-[84ch] [&_p]:text-[color:var(--color-ink)] [&_p]:text-[length:var(--text-lead)] [&_p]:font-[620] [&_p]:leading-[var(--leading-lead)] [&_p]:[text-wrap:pretty] [&_p]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]"),
  caseStudyHero: cx("grid grid-cols-[minmax(0,1fr)_minmax(18rem,0.36fr)] items-end gap-[clamp(2rem,6vw,6rem)] min-h-[min(720px,calc(100svh-78px))] border-b border-[color-mix(in_oklch,var(--color-rule),transparent_18%)] py-[clamp(4rem,9vw,7rem)] pb-[clamp(2.5rem,6vw,5rem)] text-[color:var(--color-ink)] max-[860px]:grid-cols-1 max-[860px]:min-h-0", fullBleed1180, lightGridBackground),
  caseStudyIndexHero: cx("grid grid-cols-[minmax(0,0.8fr)_minmax(24rem,1.2fr)] items-end gap-[clamp(2rem,6vw,6rem)] min-h-[min(640px,calc(100svh-78px))] border-b border-[color-mix(in_oklch,var(--color-rule),transparent_18%)] py-[clamp(4rem,9vw,7rem)] pb-[clamp(3rem,6vw,5.5rem)] text-[color:var(--color-ink)] max-[860px]:grid-cols-1 max-[860px]:min-h-0", fullBleed1180, "[background:radial-gradient(circle_at_18%_26%,color-mix(in_oklch,var(--color-blush),transparent_24%),transparent_24rem),radial-gradient(circle_at_76%_18%,color-mix(in_oklch,var(--color-sky),transparent_24%),transparent_26rem),radial-gradient(circle_at_72%_74%,color-mix(in_oklch,var(--color-mint),transparent_34%),transparent_30rem),linear-gradient(90deg,color-mix(in_oklch,var(--color-ink),transparent_95%)_1px,transparent_1px),linear-gradient(0deg,color-mix(in_oklch,var(--color-ink),transparent_96%)_1px,transparent_1px),var(--color-bg)] bg-[length:auto,auto,auto,4.5rem_4.5rem,4.5rem_4.5rem,auto]"),
  caseStudyHeroCopy: "max-w-[66rem] [&_h1]:max-w-[10ch]",
  caseIndexProofWall: "grid grid-cols-[1.1fr_0.74fr] grid-rows-2 gap-[0.8rem] h-[clamp(24rem,42vw,34rem)] m-0 max-[860px]:grid-cols-2 max-[560px]:grid-cols-1 max-[560px]:h-auto",
  caseIndexProofFrame: "h-full min-h-0 w-full overflow-hidden rounded-md border border-[color-mix(in_oklch,var(--color-rule),var(--color-ink)_8%)] bg-[var(--color-bg)] shadow-[var(--shadow-lifted)] first:row-span-2 max-[860px]:first:row-auto max-[560px]:h-auto max-[560px]:aspect-[1.85]",
  caseStudyStatus: cx("grid gap-3 rounded-lg border border-[color-mix(in_oklch,var(--color-rule),var(--color-ink)_8%)] bg-[color-mix(in_oklch,var(--color-bg),transparent_8%)] p-4 shadow-[var(--shadow-lifted)]", "[&_img]:aspect-[1.75] [&_img]:w-full [&_img]:rounded-md [&_img]:border [&_img]:border-[color-mix(in_oklch,var(--color-rule),transparent_16%)] [&_img]:bg-[var(--color-surface)] [&_img]:object-cover [&_img]:object-[center_34%]", "[&_span]:text-[color:var(--color-coral)] [&_span]:text-[length:var(--text-small)] [&_span]:font-[680] [&_span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_strong]:text-[length:var(--text-h3)] [&_strong]:font-[680] [&_strong]:leading-[1.12] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]"),
  contentSection: cx(container, "py-[clamp(2rem,5vw,4.5rem)]"),
  selectedWorkRow: "grid min-h-[9.5rem] grid-cols-[minmax(8rem,0.16fr)_minmax(12rem,0.24fr)_minmax(10rem,0.2fr)_minmax(0,1fr)_minmax(9rem,0.16fr)] items-center gap-[clamp(1rem,2vw,2rem)] border-b border-[var(--color-rule)] text-inherit no-underline max-[860px]:grid-cols-1 [&>span]:text-[color:var(--color-muted)] [&>span]:text-[length:var(--text-small)] [&>span]:font-[680] [&_em]:not-italic [&_em]:text-[color:var(--color-muted)] [&_em]:text-[length:var(--text-small)] [&_em]:font-[680] [&_p]:m-0 [&_p]:text-[color:var(--color-muted)] [&_p]:leading-[1.55] [&_p]:[text-wrap:pretty]",
  selectedWorkShot: "m-0 aspect-[1.85] overflow-hidden border border-[var(--color-rule)] bg-[var(--color-surface)] max-[560px]:max-w-[32rem] [&>span]:grid [&>span]:h-full [&>span]:w-full [&>span]:place-items-center [&>span]:text-center [&>span]:text-[color:var(--color-muted)] [&>span]:text-[length:var(--text-caption)] [&>span]:font-[680]",
  selectedWorkTitle: cx(displayFont, "text-[1.6rem] font-[680] leading-[1.12]"),
  studyRow: "grid grid-cols-[minmax(12rem,0.34fr)_minmax(0,1fr)] gap-[clamp(1rem,3vw,3rem)] border-b border-[var(--color-rule)] py-[1.6rem] max-[860px]:grid-cols-1 [&_h3]:text-[length:var(--text-h3)] [&_p]:m-0 [&_p]:max-w-[78ch] [&_p]:text-[color:var(--color-muted)] [&_p]:[text-wrap:pretty]",
  evidenceLink: cx("grid min-h-[88px] grid-cols-[minmax(12rem,0.34fr)_minmax(0,1fr)] items-center gap-[clamp(1rem,3vw,3rem)] border-b border-[var(--color-rule)] py-[1.6rem] text-inherit no-underline max-[860px]:grid-cols-1", "[&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-small)] [&_span]:font-[680] [&_span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_strong]:text-[length:var(--text-lead)] [&_strong]:font-[620] [&_strong]:leading-[var(--leading-lead)] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]"),
  confidentiality: cx(container, "my-[clamp(1rem,4vw,3rem)] mb-[clamp(4rem,8vw,7rem)] border-y border-[var(--color-dark)] py-[clamp(1.5rem,4vw,3rem)] [&_h2]:mb-4 [&_h2]:max-w-[18ch] [&_p]:m-0 [&_p]:max-w-[84ch] [&_p]:text-[color:var(--color-muted)] [&_p]:text-[length:var(--text-lead)] [&_p]:leading-[var(--leading-lead)] [&_p]:[text-wrap:pretty]"),
  resumeHero: cx("grid grid-cols-[minmax(22rem,0.46fr)_minmax(34rem,0.54fr)] items-center gap-[clamp(2rem,5vw,5rem)] min-h-[min(780px,calc(100svh-78px))] py-[clamp(3.5rem,7vw,7rem)] text-[color:var(--color-dark-ink)] shadow-[inset_0_-1px_var(--color-dark-rule)] max-[860px]:grid-cols-1 max-[860px]:min-h-0", fullBleed1320, "[background:linear-gradient(90deg,color-mix(in_oklch,var(--color-mint),transparent_91%)_1px,transparent_1px),linear-gradient(0deg,color-mix(in_oklch,var(--color-primary),transparent_93%)_1px,transparent_1px),var(--color-dark)] bg-[length:4.5rem_4.5rem,4.5rem_4.5rem,auto]"),
  resumeIdentity: "max-w-[42rem]",
  resumeRole: cx(displayFont, "m-0 mb-4 text-[color:var(--color-dark-muted)] text-[length:var(--text-h3)] font-[680] leading-[1.12]"),
  resumeProofPanel: "grid min-w-0 content-center gap-4 self-stretch",
  resumeProofCopy: cx("grid gap-[0.65rem] border-y border-[var(--color-dark-rule)] py-4", "[&_span]:text-[color:var(--color-dark-honey)] [&_span]:text-[length:var(--text-small)] [&_span]:font-[680] [&_span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_strong]:max-w-[18ch] [&_strong]:text-[color:var(--color-dark-ink)] [&_strong]:text-[length:var(--text-h3)] [&_strong]:font-[680] [&_strong]:leading-[1.08] [&_strong]:[text-wrap:balance] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_p]:m-0 [&_p]:max-w-[58ch] [&_p]:text-[color:var(--color-dark-muted)] [&_p]:leading-[var(--leading-dark-body)] [&_p]:[text-wrap:pretty]"),
  resumeContact: cx("grid gap-[0.85rem] border-y border-[var(--color-dark-rule)] py-4", "[&_>span]:text-[color:var(--color-dark-muted)] [&_>span]:text-[length:var(--text-small)] [&_>span]:font-[680] [&_>span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_a]:grid [&_a]:min-h-11 [&_a]:border-t [&_a]:border-[var(--color-dark-rule)] [&_a]:pt-3 [&_a]:text-[color:var(--color-dark-ink)] [&_a]:no-underline", "[&_strong]:text-[color:var(--color-dark-honey)] [&_strong]:text-[length:var(--text-caption)] [&_strong]:font-[680] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_a_span]:text-[color:var(--color-dark-muted)] [&_a_span]:[overflow-wrap:anywhere]"),
  resumeCopy: "grid max-w-[86ch] gap-4 border-t border-[var(--color-dark)] pt-[1.4rem] [&_p]:m-0 [&_p]:text-[color:var(--color-muted)] [&_p]:text-[length:var(--text-lead)] [&_p]:leading-[var(--leading-lead)] [&_p]:[text-wrap:pretty]",
  resumeRow: "grid grid-cols-[minmax(10rem,0.28fr)_minmax(0,1fr)] gap-[clamp(1rem,3vw,3rem)] border-b border-[var(--color-rule)] py-[1.35rem] max-[860px]:grid-cols-1 [&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-small)] [&_span]:font-[680] [&_p]:m-0 [&_p]:max-w-[82ch] [&_p]:text-[color:var(--color-muted)] [&_p]:[text-wrap:pretty] [&_strong]:text-[color:var(--color-ink)] [&_strong]:font-[680]",
  resumeEntry: "grid gap-3 border-b border-[var(--color-rule)] py-[1.6rem] [&_h3]:text-[length:var(--text-h3)] [&_p]:m-0 [&_p]:max-w-[86ch] [&_p]:text-[color:var(--color-muted)] [&_p]:[text-wrap:pretty] [&_ul]:m-0 [&_ul]:grid [&_ul]:max-w-[86ch] [&_ul]:gap-[0.45rem] [&_ul]:pl-5 [&_ul]:text-[color:var(--color-muted)] [&_ul]:[text-wrap:pretty]",
  resumeEntryHeading: "grid grid-cols-[minmax(0,1fr)_auto] items-baseline gap-4 max-[860px]:grid-cols-1 [&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-small)] [&_span]:font-[680]",
  routeHero: cx(container, "grid grid-cols-[minmax(0,0.92fr)_minmax(17rem,0.34fr)] items-end gap-[clamp(2rem,7vw,7rem)] min-h-[min(680px,calc(100svh-78px))] py-[clamp(4rem,10vw,8rem)] pb-[clamp(2.5rem,6vw,5rem)] max-[860px]:grid-cols-1 max-[860px]:min-h-0"),
  routeHeroCopy: "max-w-[58rem] [&_h1]:max-w-[12ch]",
  routePanel: cx("grid gap-[0.45rem] border-y border-[var(--color-dark)] py-4", displayFont, "[&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-caption)] [&_span]:font-[650]", "[&_strong]:mb-[0.65rem] [&_strong]:text-[1.12rem] [&_strong]:leading-[1.2] [&_strong]:[overflow-wrap:anywhere]"),
  routeProofSection: cx(container, "py-[clamp(2rem,6vw,5rem)] pb-[clamp(4rem,9vw,7.5rem)]"),
  routeProofItem: "grid grid-cols-[minmax(8rem,0.28fr)_minmax(0,1fr)] gap-5 border-b border-[var(--color-rule)] py-[1.35rem] max-[860px]:grid-cols-1 [&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-caption)] [&_span]:font-[650] [&_p]:m-0 [&_p]:max-w-[68ch] [&_p]:text-[color:var(--color-muted)] [&_p]:[text-wrap:pretty]",
  privacyBoundaryNote: cx(displayFont, "mt-[clamp(1rem,3vw,2rem)] mb-0 max-w-[84ch] border-t border-[var(--color-rule)] pt-4 text-[color:var(--color-ink)] text-[length:var(--text-lead)] font-[620] leading-[var(--leading-lead)] [text-wrap:pretty]"),
} as const;

export function proofImageClass(kind = "site") {
  return cx(
    ui.proofImage,
    kind === "landing" && "object-top [transform:scale(1.08)] [transform-origin:50%_8%]",
    kind === "dashboard" && "object-left-top [transform:scale(1.32)] [transform-origin:18%_8%]",
  );
}

export function screenshotImageClass(kind = "site", scale: "normal" | "compact" = "normal") {
  return cx(
    "block h-full w-full object-cover object-[center_34%] [filter:saturate(1.05)_contrast(1.04)]",
    kind === "landing" && "object-[center_18%] [transform:scale(1.08)] [transform-origin:50%_12%]",
    kind === "dashboard" && (scale === "compact"
      ? "object-left-top [transform:scale(1.28)] [transform-origin:16%_8%]"
      : "object-left-top [transform:scale(1.3)] [transform-origin:16%_8%]"),
    kind === "diagram" && "object-center [transform:scale(1.02)]",
  );
}
