type ClassValue = false | null | string | undefined;

export function cx(...values: ClassValue[]) {
  return values.filter(Boolean).join(" ");
}

const focusRing = "focus-visible:[outline:3px_solid_var(--color-focus)] focus-visible:outline-offset-4";
const displayFont = "[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]";
const bodyFont = "[font-family:'Atkinson_Hyperlegible_Next_Variable','Atkinson_Hyperlegible_Next',ui-sans-serif,system-ui,sans-serif]";
const editorialFont = "[font-family:'Iowan_Old_Style','Palatino_Linotype',Georgia,ui-serif,serif]";
const container = "w-[var(--container)] mx-auto";
const fullBleed1180 = "w-full mx-0 px-[max(1rem,calc((100vw-1180px)/2))]";
const fullBleed1320 = "w-full mx-0 px-[max(1.25rem,calc((100vw-1320px)/2))]";
const darkGridBackground = "[background:linear-gradient(90deg,color-mix(in_oklch,var(--color-sky),transparent_90%)_1px,transparent_1px),linear-gradient(0deg,color-mix(in_oklch,var(--color-mint),transparent_91%)_1px,transparent_1px),var(--color-dark)] bg-[length:4.5rem_4.5rem,4.5rem_4.5rem,auto]";
const lightGridBackground = "[background:radial-gradient(circle_at_14%_24%,color-mix(in_oklch,var(--color-aqua-soft),transparent_20%),transparent_24rem),radial-gradient(circle_at_82%_18%,color-mix(in_oklch,var(--color-lilac),transparent_28%),transparent_26rem),linear-gradient(90deg,color-mix(in_oklch,var(--color-ink),transparent_95%)_1px,transparent_1px),linear-gradient(0deg,color-mix(in_oklch,var(--color-ink),transparent_96%)_1px,transparent_1px),var(--color-bg)] bg-[length:auto,auto,4.5rem_4.5rem,4.5rem_4.5rem,auto]";

export const themeVars = cx(
  "[color-scheme:light]",
  "[--color-bg:oklch(0.998_0.002_100)]",
  "[--color-surface:oklch(0.982_0.004_110)]",
  "[--color-ink:oklch(0.19_0.018_252)]",
  "[--color-muted:oklch(0.43_0.026_238)]",
  "[--color-rule:oklch(0.89_0.006_245)]",
  "[--color-primary:oklch(0.78_0.13_78)]",
  "[--color-primary-ink:oklch(0.15_0.015_80)]",
  "[--color-mint:oklch(0.82_0.105_162)]",
  "[--color-mint-ink:oklch(0.18_0.04_165)]",
  "[--color-sky:oklch(0.82_0.085_230)]",
  "[--color-sky-ink:oklch(0.18_0.04_245)]",
  "[--color-coral:oklch(0.78_0.13_35)]",
  "[--color-blush:oklch(0.9_0.055_28)]",
  "[--color-lilac:oklch(0.89_0.05_302)]",
  "[--color-aqua-soft:oklch(0.91_0.06_185)]",
  "[--color-dark:oklch(0.09_0.006_260)]",
  "[--color-dark-surface:oklch(0.14_0.01_260)]",
  "[--color-dark-panel:oklch(0.115_0.012_260)]",
  "[--color-dark-ink:oklch(0.96_0.01_160)]",
  "[--color-dark-muted:oklch(0.76_0.035_180)]",
  "[--color-dark-rule:color-mix(in_oklch,var(--color-dark-ink),transparent_78%)]",
  "[--color-dark-honey:oklch(0.78_0.13_78)]",
  "[--color-dark-mint-panel:color-mix(in_oklch,var(--color-mint),var(--color-dark)_86%)]",
  "[--color-honey-soft:oklch(0.92_0.08_82)]",
  "[--color-focus:oklch(0.48_0.16_255)]",
  "[--text-caption:0.8125rem]",
  "[--text-small:0.875rem]",
  "[--text-body:1rem]",
  "[--text-lead:1.25rem]",
  "[--text-h3:1.75rem]",
  "[--text-h2:3.25rem]",
  "[--text-hero:4.25rem]",
  "[--text-home-hero:4.05rem]",
  "[--leading-caption:1.35]",
  "[--leading-body:1.62]",
  "[--leading-lead:1.45]",
  "[--leading-heading:1.04]",
  "[--leading-dark-body:1.7]",
  "[--container:min(100%_-_clamp(1rem,4vw,3rem),1180px)]",
  "[--container-wide:min(100%_-_clamp(1rem,4vw,3rem),1440px)]",
  "[--shadow-soft:0_1.35rem_4rem_color-mix(in_oklch,var(--color-sky-ink),transparent_88%)]",
  "[--shadow-lifted:0_1rem_2.6rem_color-mix(in_oklch,var(--color-ink),transparent_90%)]",
  "max-[860px]:[--text-h2:2.65rem]",
  "max-[860px]:[--text-hero:3.35rem]",
  "max-[860px]:[--text-home-hero:3.35rem]",
  "max-[560px]:[--container:min(100%_-_1.2rem,1180px)]",
  "max-[560px]:[--text-lead:1.125rem]",
  "max-[560px]:[--text-h3:1.5rem]",
  "max-[560px]:[--text-h2:2.1rem]",
  "max-[560px]:[--text-hero:2.65rem]",
  "max-[560px]:[--text-home-hero:2.65rem]",
);

export const bodyClass = cx(
  themeVars,
  bodyFont,
  "m-0 overflow-x-hidden bg-[var(--color-bg)] text-[color:var(--color-ink)] text-[length:var(--text-body)] leading-[var(--leading-body)] [overflow-wrap:break-word] [text-rendering:optimizeLegibility]",
);

export const ui = {
  siteShell: cx(
    "min-h-screen overflow-x-hidden",
    "[&_main]:min-w-0 [&_section]:min-w-0 [&_figure]:min-w-0",
    "[&_a]:text-inherit",
    "[&_h1]:m-0 [&_h1]:max-w-[15ch] [&_h1]:text-[length:var(--text-hero)] [&_h1]:font-[500] [&_h1]:leading-[var(--leading-heading)] [&_h1]:tracking-normal [&_h1]:[overflow-wrap:normal] [&_h1]:[text-wrap:balance]",
    "[&_h1]:[font-family:'Iowan_Old_Style','Palatino_Linotype',Georgia,ui-serif,serif]",
    "[&_h2]:m-0 [&_h2]:max-w-[15ch] [&_h2]:text-[length:var(--text-h2)] [&_h2]:font-[520] [&_h2]:leading-[var(--leading-heading)] [&_h2]:tracking-normal [&_h2]:[overflow-wrap:normal] [&_h2]:[text-wrap:balance]",
    "[&_h2]:[font-family:'Iowan_Old_Style','Palatino_Linotype',Georgia,ui-serif,serif]",
    "[&_h3]:m-0 [&_h3]:leading-[var(--leading-heading)] [&_h3]:tracking-normal [&_h3]:[overflow-wrap:normal] [&_h3]:[text-wrap:balance]",
    "[&_h3]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]",
  ),
  skipLink: cx(
    focusRing,
    displayFont,
    "fixed top-4 left-4 z-10 -translate-y-[150%] border border-[var(--color-dark)] bg-[var(--color-bg)] px-[0.9rem] py-[0.7rem] font-[520] focus:translate-y-0 focus-visible:translate-y-0",
  ),
  siteHeader: "sticky top-0 z-[5] border-b border-[var(--color-rule)] bg-[color-mix(in_oklch,var(--color-bg),transparent_4%)] text-[color:var(--color-ink)] backdrop-blur-[14px]",
  siteNav: cx("mx-auto grid w-full max-w-[1440px] grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-4 px-6 py-4 max-[860px]:grid-cols-[auto_1fr] max-[860px]:gap-y-2 max-[560px]:px-4"),
  brandLockup: "flex min-w-max items-center gap-2 no-underline max-[560px]:min-w-11",
  brandSymbol: "hidden",
  brandMark: "hidden",
  brandText: cx(displayFont, "grid font-[760] leading-[1.05] tracking-normal [&_span]:text-[length:var(--text-small)] [&_small]:hidden"),
  navLinks: cx(
    displayFont,
    "flex items-center justify-center gap-[clamp(0.65rem,1.6vw,1.6rem)] text-[length:var(--text-small)] font-[680] max-[860px]:order-3 max-[860px]:col-span-2 max-[860px]:justify-start max-[860px]:overflow-x-auto max-[860px]:whitespace-nowrap max-[860px]:[scrollbar-width:none] max-[860px]:[&::-webkit-scrollbar]:hidden",
    "[&_a]:inline-flex [&_a]:min-h-10 [&_a]:items-center [&_a]:rounded-sm [&_a]:px-2 [&_a]:no-underline [&_a]:decoration-1 [&_a]:underline-offset-[0.25em] [&_a:hover]:bg-[color-mix(in_oklch,var(--color-sky),var(--color-bg)_86%)]",
  ),
  navActions: cx(displayFont, "flex items-center justify-end gap-3 text-[length:var(--text-caption)] font-[760]"),
  navLanguage: cx(focusRing, "inline-flex size-8 items-center justify-center border border-[var(--color-rule)] bg-[var(--color-bg)] text-[length:0.68rem] no-underline"),
  navCta: cx(focusRing, "inline-flex min-h-9 items-center justify-center border border-[color-mix(in_oklch,var(--color-primary),var(--color-dark)_12%)] bg-[var(--color-primary)] px-4 text-[color:var(--color-primary-ink)] no-underline"),
  siteFooter: cx("mx-auto grid w-full max-w-[1440px] grid-cols-[minmax(10rem,0.24fr)_minmax(0,1fr)_minmax(14rem,0.28fr)] items-end gap-8 border-t border-[var(--color-rule)] px-6 py-9 max-[860px]:grid-cols-1 max-[560px]:px-4 [&_p]:m-0 [&_p]:max-w-[34ch] [&_p]:text-[color:var(--color-muted)] [&_p]:text-[length:var(--text-caption)]"),
  footerKicker: cx(displayFont, "mb-[0.3rem] !text-[color:var(--color-ink)] font-bold"),
  footerLinks: cx(displayFont, "flex flex-wrap justify-center gap-8 text-[length:var(--text-caption)] font-[680] max-[860px]:justify-start [&_a]:inline-flex [&_a]:min-h-10 [&_a]:items-center [&_a]:no-underline [&_a]:decoration-1 [&_a]:underline-offset-[0.25em]"),
  footerDashboardLink: "inline-flex min-h-10 items-center border border-[var(--color-rule)] bg-[var(--color-bg)] px-3 text-[color:var(--color-ink)] no-underline",
  copyright: "col-span-full text-[length:var(--text-caption)] [font-variant-numeric:tabular-nums]",
  sectionContainer: container,
  fullBleed1180,
  fullBleed1320,
  signalLine: cx(displayFont, "m-0 mb-5 text-[color:var(--color-muted)] text-[length:var(--text-small)] font-[680]"),
  heroLead: "mt-[1.6rem] mb-0 max-w-[60ch] text-[color:var(--color-muted)] text-[length:var(--text-lead)] leading-[var(--leading-lead)] [text-wrap:pretty] max-[560px]:mt-[1.05rem]",
  heroActions: "mt-8 flex flex-wrap items-center gap-[0.85rem] max-[560px]:mt-[1.3rem] max-[560px]:gap-[0.65rem]",
  button: cx(focusRing, displayFont, "inline-flex min-h-12 items-center justify-center border border-[var(--color-dark)] px-4 py-[0.85rem] text-[length:var(--text-small)] font-[680] no-underline disabled:opacity-70"),
  buttonPrimary: "bg-[var(--color-primary)] text-[color:var(--color-primary-ink)]",
  buttonSecondary: "bg-[var(--color-bg)]",
  buttonSecondaryOnLightHero: "border-[color-mix(in_oklch,var(--color-ink),transparent_76%)] bg-[color-mix(in_oklch,var(--color-bg),transparent_14%)] text-[color:var(--color-ink)]",
  buttonSecondaryOnDark: "border-[var(--color-dark-rule)] bg-transparent text-[color:var(--color-dark-ink)]",
  buttonWhatsapp: "border-[var(--color-mint-ink)] bg-[var(--color-mint)] text-[color:var(--color-mint-ink)]",
  sectionHeading: "mb-[clamp(2rem,5vw,4rem)] grid gap-[0.2rem]",
  sectionIntro: "mt-4 mb-0 max-w-[62ch] text-[color:var(--color-muted)] text-[length:var(--text-lead)] leading-[var(--leading-lead)] [text-wrap:pretty]",
  homeProofHero: cx(
    "grid w-full grid-cols-[minmax(20rem,0.45fr)_minmax(30rem,0.55fr)] items-center gap-[clamp(2rem,6vw,5.5rem)] border-b border-[var(--color-rule)] py-[clamp(4.5rem,7vw,6.5rem)] text-[color:var(--color-ink)] max-[980px]:grid-cols-1",
    fullBleed1320,
    "[background:linear-gradient(90deg,color-mix(in_oklch,var(--color-ink),transparent_94%)_1px,transparent_1px),linear-gradient(0deg,color-mix(in_oklch,var(--color-ink),transparent_96%)_1px,transparent_1px),var(--color-bg)] bg-[length:3.25rem_3.25rem,3.25rem_3.25rem,auto]",
  ),
  homeHeroCopy: "relative z-[2] grid max-w-[44rem] justify-items-start text-left",
  homeHeroActions: "justify-start",
  homeSignalLine: cx(displayFont, "!mb-5 !text-[color:var(--color-primary)] uppercase text-[length:var(--text-caption)] [font-variant-caps:all-small-caps] before:mr-2 before:inline-block before:size-2 before:rounded-full before:bg-[var(--color-primary)] before:content-['']"),
  darkSignalLine: "!text-[color:var(--color-dark-honey)]",
  homeHeadline: cx(editorialFont, "max-w-[18ch] text-[length:var(--text-home-hero)] font-[500] tracking-normal [&>span]:block [&>span]:whitespace-nowrap [&_em]:font-[400] [&_em]:italic max-[700px]:[&>span]:whitespace-normal max-[560px]:max-w-[10.5ch] max-[560px]:text-[length:var(--text-hero)]"),
  homeHeroLead: "max-w-[45ch] text-[color:var(--color-muted)] text-[length:1.06rem] leading-[1.62] [overflow-wrap:break-word] max-[560px]:w-full max-[560px]:max-w-[calc(100vw-2rem)]",
  homeStackStrip: cx(displayFont, "mt-[clamp(2.5rem,5vw,4rem)] grid w-full grid-cols-4 gap-3 text-[length:var(--text-caption)] text-[color:var(--color-muted)] max-[760px]:grid-cols-2 max-[460px]:grid-cols-1", "[&_span]:grid [&_span]:grid-cols-[auto_1fr] [&_span]:items-center [&_span]:gap-2", "[&_span]:before:block [&_span]:before:size-3 [&_span]:before:rounded-full [&_span]:before:border [&_span]:before:border-[var(--color-rule)] [&_span]:before:bg-[var(--color-bg)] [&_span]:before:content-['']", "[&_strong]:block [&_strong]:text-[color:var(--color-ink)] [&_strong]:font-[760]"),
  homeSystemBoard: cx("relative m-0 min-h-[36rem] overflow-hidden border-l border-[var(--color-rule)] bg-[color-mix(in_oklch,var(--color-bg),transparent_1%)] max-[980px]:min-h-[32rem] max-[560px]:min-h-[28rem] max-[560px]:border-l-0", "[background:linear-gradient(90deg,color-mix(in_oklch,var(--color-ink),transparent_92%)_1px,transparent_1px),linear-gradient(0deg,color-mix(in_oklch,var(--color-ink),transparent_95%)_1px,transparent_1px)] bg-[length:2.35rem_2.35rem]"),
  homeBoardLabel: cx(displayFont, "absolute left-[7%] top-[11%] text-[length:var(--text-caption)] font-[680] text-[color:var(--color-muted)]"),
  homeSystemMap: "absolute left-[14%] top-[17%] grid w-[min(58%,28rem)] grid-cols-3 gap-4 max-[560px]:left-5 max-[560px]:top-16 max-[560px]:w-[calc(100%-2.5rem)]",
  systemNodePrimary: cx(displayFont, "col-span-3 justify-self-center border border-[var(--color-ink)] bg-[var(--color-bg)] px-5 py-3 text-[length:var(--text-caption)] font-[760] uppercase"),
  systemNode: cx("relative z-[2] grid min-h-[6.5rem] content-start gap-1 border border-[color-mix(in_oklch,var(--color-ink),transparent_26%)] bg-[color-mix(in_oklch,var(--color-bg),transparent_3%)] px-4 py-3 max-[560px]:px-3", "[&_strong]:text-[length:var(--text-caption)] [&_strong]:font-[760] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_small]:text-[length:0.72rem] [&_small]:text-[color:var(--color-muted)]", "[&_span]:text-[length:0.68rem] [&_span]:text-[color:var(--color-muted)]"),
  systemConnector: "absolute left-[calc(14%+14rem)] top-[24%] h-[7rem] w-px bg-[color-mix(in_oklch,var(--color-ink),transparent_55%)] max-[560px]:hidden",
  systemConnectorSecondary: "absolute left-[26%] top-[38%] h-px w-[34%] bg-[color-mix(in_oklch,var(--color-ink),transparent_55%)] max-[560px]:hidden",
  homeMiniScreenshot: "absolute right-[7%] top-[13%] block w-[12.5rem] overflow-hidden border border-[color-mix(in_oklch,var(--color-ink),transparent_28%)] bg-[var(--color-bg)] shadow-[var(--shadow-lifted)] max-[560px]:hidden [&_img]:aspect-[1.45] [&_img]:w-full",
  homeStickyNote: cx("absolute right-[14%] top-[42%] grid w-[8rem] rotate-[-8deg] gap-2 bg-[var(--color-primary)] px-4 py-4 text-[color:var(--color-primary-ink)] shadow-[var(--shadow-lifted)] max-[560px]:right-5 max-[560px]:top-auto max-[560px]:bottom-14", "[&_strong]:text-[length:var(--text-small)] [&_strong]:font-[760] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_span]:text-[length:0.72rem]"),
  homePen: "absolute right-[4%] top-[18%] block h-[18rem] w-3 rounded-full bg-[var(--color-ink)] shadow-[var(--shadow-lifted)] after:absolute after:left-1/2 after:top-2 after:h-[2rem] after:w-px after:-translate-x-1/2 after:bg-[color-mix(in_oklch,var(--color-bg),transparent_30%)] after:content-[''] max-[560px]:hidden",
  homeChartCard: cx("absolute bottom-[12%] left-[9%] grid h-[7rem] w-[11rem] grid-cols-4 items-end gap-2 border border-[var(--color-rule)] bg-[var(--color-bg)] p-4 shadow-[var(--shadow-lifted)] max-[560px]:hidden", "[&_span]:block [&_span]:bg-[var(--color-sky)] [&_span:nth-child(1)]:h-[36%] [&_span:nth-child(2)]:h-[58%] [&_span:nth-child(3)]:h-[42%] [&_span:nth-child(4)]:h-[76%]"),
  homeCodeCard: cx("absolute bottom-[13%] right-[10%] grid w-[16rem] rotate-[4deg] gap-2 border border-[var(--color-rule)] bg-[var(--color-dark)] p-4 shadow-[var(--shadow-lifted)] max-[760px]:right-5 max-[560px]:hidden", "[&_span]:block [&_span]:h-2 [&_span]:rounded-full [&_span]:bg-[color-mix(in_oklch,var(--color-dark-ink),transparent_26%)] [&_span:nth-child(2)]:w-[72%] [&_span:nth-child(3)]:w-[86%] [&_span:nth-child(4)]:w-[54%]"),
  homeBoardCaption: cx("absolute bottom-[21%] left-[45%] grid max-w-[14rem] gap-1 text-[color:var(--color-muted)] max-[760px]:hidden", "[&_strong]:text-[color:var(--color-ink)] [&_strong]:text-[length:var(--text-small)] [&_strong]:font-[680] [&_strong]:leading-[1.2] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_span]:text-[length:var(--text-caption)] [&_span]:leading-[var(--leading-caption)]"),
  proofImage: "block h-full w-full object-cover object-[center_30%] [filter:saturate(1.04)_contrast(1.03)]",
  proofMetricStrip: "mx-auto mt-[-1px] grid w-[var(--container)] grid-cols-5 overflow-hidden border border-[var(--color-rule)] bg-[var(--color-bg)] max-[980px]:grid-cols-2 max-[560px]:grid-cols-1",
  proofMetric: cx("grid min-h-[7.7rem] content-center justify-items-center gap-[0.3rem] border-r border-[var(--color-rule)] px-[clamp(0.85rem,1.8vw,1.2rem)] py-5 text-center last:border-r-0 max-[980px]:border-b max-[980px]:[&:nth-child(2n)]:border-r-0 max-[560px]:border-r-0", "[&_strong]:text-[length:var(--text-h3)] [&_strong]:leading-[1] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&:nth-child(1)_strong]:text-[color:var(--color-primary)] [&:nth-child(2)_strong]:text-[color:var(--color-mint-ink)] [&:nth-child(3)_strong]:text-[color:var(--color-sky-ink)] [&:nth-child(4)_strong]:text-[color:var(--color-coral)] [&:nth-child(5)_strong]:text-[color:var(--color-mint-ink)]", "[&_span]:text-[color:var(--color-ink)] [&_span]:text-[length:var(--text-caption)] [&_span]:font-[760] [&_span]:leading-[1.15] [&_span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_p]:m-0 [&_p]:max-w-[16ch] [&_p]:text-[color:var(--color-muted)] [&_p]:text-[length:0.68rem] [&_p]:leading-[1.25]"),
  selectedOutcomes: "w-full px-[max(1rem,calc((100vw-1180px)/2))] py-[clamp(4rem,8vw,6.25rem)]",
  sectionTextLink: cx(displayFont, "self-end justify-self-end text-[length:var(--text-caption)] font-[760] text-[color:var(--color-ink)] no-underline max-[700px]:justify-self-start"),
  outcomeLedger: "grid overflow-hidden border border-[var(--color-rule)] border-b-0 bg-[var(--color-bg)]",
  outcomeRow: "group grid min-h-[9.1rem] grid-cols-[minmax(15rem,0.31fr)_minmax(15rem,0.32fr)_minmax(8rem,0.17fr)_minmax(8rem,0.14fr)_minmax(7rem,0.12fr)] items-stretch text-inherit no-underline max-[980px]:grid-cols-1",
  outcomeShot: "m-0 overflow-hidden border-r border-b border-[var(--color-rule)] bg-[var(--color-surface)] max-[980px]:aspect-[1.9] max-[980px]:border-r-0",
  evidenceFallback: cx(displayFont, "grid h-full w-full place-items-center border border-[var(--color-rule)] bg-[color-mix(in_oklch,var(--color-surface),var(--color-mint)_9%)] text-center text-[color:var(--color-muted)] text-[length:var(--text-caption)] font-[680]"),
  outcomeSummary: "grid content-center gap-[0.5rem] border-b border-r border-[var(--color-rule)] px-8 py-5 max-[980px]:border-r-0 max-[980px]:px-5",
  outcomeStatus: cx(displayFont, "flex flex-wrap items-center gap-2 text-[length:1.25rem] font-[760] leading-[1.12]", "[&_small]:text-[color:var(--color-mint-ink)] [&_small]:text-[length:var(--text-caption)] [&_small]:font-[680] [&_small]:before:mr-1 [&_small]:before:inline-block [&_small]:before:size-1.5 [&_small]:before:rounded-full [&_small]:before:bg-[var(--color-mint)] [&_small]:before:content-['']"),
  outcomeMeta: cx("grid content-center gap-2 border-b border-r border-[var(--color-rule)] px-6 py-5 max-[980px]:border-r-0 max-[980px]:px-5", "[&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:0.68rem] [&_span]:font-[680] [&_span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_strong]:text-[length:var(--text-small)] [&_strong]:font-[680] [&_strong]:leading-[1.25] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]"),
  bodyMutedPretty: "m-0 text-[color:var(--color-muted)] leading-[1.55] [text-wrap:pretty]",
  outcomeCta: cx(displayFont, "grid content-center border-b border-[var(--color-rule)] px-5 py-5 text-[length:var(--text-caption)] font-[760] text-[color:var(--color-ink)] transition-transform duration-[180ms] ease-out group-hover:translate-x-1 motion-reduce:transition-none"),
  architectureStage: cx("grid w-full grid-cols-[minmax(18rem,0.34fr)_minmax(0,0.66fr)] gap-[clamp(2rem,6vw,5rem)] border-y border-[var(--color-dark-rule)] px-[max(1rem,calc((100vw-1180px)/2))] py-[clamp(4rem,8vw,5.75rem)] text-[color:var(--color-dark-ink)] max-[980px]:grid-cols-1", darkGridBackground),
  architectureStageCopy: "min-w-0 self-center [&_h2]:max-w-[12ch]",
  architectureLead: "mt-5 mb-0 max-w-[52ch] text-[color:var(--color-dark-muted)] text-[length:1rem] leading-[var(--leading-dark-body)] [text-wrap:pretty]",
  framedImage: "m-0 overflow-hidden border border-[color-mix(in_oklch,var(--color-rule),var(--color-ink)_8%)] bg-[var(--color-bg)] shadow-[var(--shadow-lifted)]",
  architectureDiagram: "grid content-center gap-10 self-stretch",
  architectureDiagramRow: "relative grid grid-cols-3 gap-[clamp(1rem,3vw,4rem)] before:absolute before:left-[16%] before:right-[16%] before:top-1/2 before:h-px before:bg-[var(--color-dark-rule)] before:content-[''] max-[700px]:grid-cols-1 max-[700px]:before:hidden",
  architectureDiagramNode: cx("relative z-[2] grid min-h-[8rem] gap-2 border border-[var(--color-dark-rule)] bg-[var(--color-dark-panel)] px-5 py-4", "[&_strong]:text-[color:var(--color-dark-ink)] [&_strong]:text-[length:var(--text-small)] [&_strong]:font-[760] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_span]:text-[color:var(--color-dark-muted)] [&_span]:text-[length:var(--text-caption)]", "[&_small]:text-[color:var(--color-dark-muted)] [&_small]:text-[length:0.7rem]"),
  architectureServiceRow: "grid grid-cols-3 gap-[clamp(1rem,3vw,4rem)] max-[700px]:grid-cols-1",
  architectureServiceNode: cx("grid justify-items-center gap-1 border border-[var(--color-dark-rule)] bg-[var(--color-dark-panel)] px-5 py-4 text-center", "[&_strong]:text-[color:var(--color-dark-ink)] [&_strong]:text-[length:var(--text-small)] [&_strong]:font-[760] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_span]:text-[color:var(--color-dark-muted)] [&_span]:text-[length:var(--text-caption)]"),
  architectureToolGrid: cx(displayFont, "col-span-full mt-3 grid grid-cols-4 border-t border-[var(--color-dark-rule)] pt-6 text-[length:var(--text-caption)] text-[color:var(--color-dark-muted)] max-[980px]:grid-cols-2 max-[560px]:grid-cols-1", "[&_span]:grid [&_span]:gap-1 [&_span]:px-3 [&_span]:py-2", "[&_strong]:text-[color:var(--color-dark-ink)] [&_strong]:font-[760]"),
  practiceSection: cx(container, "grid grid-cols-[minmax(0,0.38fr)_minmax(28rem,0.62fr)] items-start gap-[clamp(2rem,6vw,5rem)] py-[clamp(4rem,8vw,6rem)] max-[980px]:grid-cols-1"),
  practiceList: "grid border-t border-[var(--color-rule)]",
  practiceItem: "grid grid-cols-[3rem_minmax(0,1fr)] gap-5 border-b border-[var(--color-rule)] py-6 max-[560px]:grid-cols-1 [&_strong]:text-[color:var(--color-ink)] [&_strong]:text-[length:var(--text-small)] [&_strong]:font-[760] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif] [&_p]:m-0 [&_p]:mt-1 [&_p]:max-w-[58ch] [&_p]:text-[color:var(--color-muted)] [&_p]:text-[length:var(--text-small)] [&_p]:leading-[1.55]",
  practiceIcon: cx(displayFont, "grid size-10 place-items-center rounded-full border border-[var(--color-rule)] bg-[color-mix(in_oklch,var(--color-primary),var(--color-bg)_76%)] text-[length:0.72rem] font-[760] text-[color:var(--color-primary-ink)]"),
  practiceArtifact: "m-0 overflow-hidden border border-[var(--color-rule)] bg-[var(--color-bg)] shadow-[var(--shadow-lifted)]",
  practiceArtifactPanel: cx("grid min-h-[30rem] content-start", "[background:linear-gradient(90deg,color-mix(in_oklch,var(--color-ink),transparent_95%)_1px,transparent_1px),linear-gradient(0deg,color-mix(in_oklch,var(--color-ink),transparent_96%)_1px,transparent_1px),var(--color-bg)] bg-[length:3rem_3rem,3rem_3rem,auto]"),
  practiceArtifactChrome: "flex h-10 items-center gap-1.5 border-b border-[var(--color-rule)] px-4 [&_span]:block [&_span]:size-2 [&_span]:rounded-full [&_span]:bg-[var(--color-rule)]",
  practiceArtifactShell: cx("grid grid-cols-[11rem_minmax(0,1fr)] min-h-[27rem] max-[700px]:grid-cols-1", "[&_aside]:grid [&_aside]:content-start [&_aside]:gap-1 [&_aside]:border-r [&_aside]:border-[var(--color-rule)] [&_aside]:bg-[color-mix(in_oklch,var(--color-surface),var(--color-bg)_45%)] [&_aside]:p-5 max-[700px]:[&_aside]:hidden", "[&_aside_span]:px-3 [&_aside_span]:py-2 [&_aside_span]:text-[color:var(--color-muted)] [&_aside_span]:text-[length:var(--text-caption)] [&_aside_span]:font-[680] [&_main]:grid [&_main]:content-start [&_main]:gap-5 [&_main]:p-8 max-[560px]:[&_main]:p-5", "[&_main>strong]:text-[length:var(--text-lead)] [&_main>strong]:font-[760] [&_main>strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]"),
  practiceArtifactStats: cx("grid grid-cols-4 gap-3 max-[700px]:grid-cols-2", "[&_span]:grid [&_span]:gap-2 [&_span]:border [&_span]:border-[var(--color-rule)] [&_span]:bg-[var(--color-bg)] [&_span]:px-4 [&_span]:py-4", "[&_small]:text-[color:var(--color-muted)] [&_small]:text-[length:0.68rem]", "[&_strong]:text-[color:var(--color-ink)] [&_strong]:text-[length:var(--text-h3)] [&_strong]:leading-[1]"),
  practiceArtifactRows: cx("grid overflow-hidden border border-[var(--color-rule)] bg-[var(--color-bg)]", "[&_span]:grid [&_span]:grid-cols-[minmax(9rem,0.34fr)_minmax(0,1fr)] [&_span]:gap-4 [&_span]:border-b [&_span]:border-[var(--color-rule)] [&_span]:px-4 [&_span]:py-3 [&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-caption)] [&_span]:leading-[1.45] [&_span:last-child]:border-b-0 max-[560px]:[&_span]:grid-cols-1", "[&_strong]:text-[color:var(--color-ink)] [&_strong]:text-[length:var(--text-caption)] [&_strong]:leading-[1.2]"),
  engagementSection: cx(container, "py-[clamp(2rem,6vw,5rem)]"),
  engagementGrid: "grid grid-cols-3 gap-6 max-[860px]:grid-cols-1",
  engagementCard: cx("grid min-h-[18rem] content-start gap-4 border border-[var(--color-rule)] bg-[var(--color-bg)] p-[clamp(1rem,2.5vw,1.7rem)]", "[&_h3]:text-[length:var(--text-lead)] [&_h3]:font-[760] [&_h3]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_p]:m-0 [&_p]:text-[color:var(--color-muted)] [&_p]:leading-[1.55]", "[&_ul]:m-0 [&_ul]:grid [&_ul]:gap-[0.45rem] [&_ul]:pl-5 [&_ul]:text-[color:var(--color-ink)] [&_ul]:text-[length:var(--text-small)]", "[&_a]:mt-auto [&_a]:inline-flex [&_a]:min-h-11 [&_a]:items-center [&_a]:border-t [&_a]:border-[var(--color-rule)] [&_a]:pt-3 [&_a]:text-[color:var(--color-ink)] [&_a]:font-[680] [&_a]:no-underline [&_a]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]"),
  engagementIcon: cx(displayFont, "grid size-12 place-items-center rounded-full bg-[color-mix(in_oklch,var(--color-primary),var(--color-bg)_62%)] text-[length:var(--text-caption)] font-[760] text-[color:var(--color-primary-ink)]"),
  contactBand: cx("grid grid-cols-[minmax(0,0.38fr)_minmax(26rem,0.62fr)] items-start gap-[clamp(2rem,6vw,5rem)] border-t border-[var(--color-rule)] py-[clamp(4rem,8vw,6rem)] text-[color:var(--color-ink)] max-[980px]:grid-cols-1 [&_p]:mt-4 [&_p]:mb-0 [&_p]:max-w-[62ch] [&_p]:text-[color:var(--color-muted)] [&_p]:leading-[var(--leading-lead)] [&_p]:[text-wrap:pretty]", fullBleed1180, "bg-[var(--color-bg)]"),
  faqList: "mt-8 grid overflow-hidden border border-[var(--color-rule)] bg-[var(--color-bg)]",
  faqItem: cx("border-b border-[var(--color-rule)] px-4 py-4 last:border-b-0", "[&_summary]:cursor-pointer [&_summary]:text-[color:var(--color-ink)] [&_summary]:font-[680] [&_summary]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_p]:text-[length:var(--text-body)]"),
  contactCard: cx("grid gap-5 border border-[var(--color-rule)] bg-[var(--color-bg)] p-[clamp(1rem,2.6vw,1.8rem)]", "[&_h2]:max-w-[18ch]", "[&_p]:text-[length:var(--text-body)]"),
  contactCardIntro: "grid gap-0",
  homeContactForm: "grid gap-4",
  contactActions: cx(displayFont, "grid grid-cols-3 gap-0 border-t border-[var(--color-rule)] pt-4 text-[length:var(--text-caption)] font-[680] max-[700px]:grid-cols-1", "[&_a]:min-h-10 [&_a]:content-center [&_a]:text-[color:var(--color-muted)] [&_a]:no-underline [&_a]:[overflow-wrap:anywhere]"),
  contactFormSection: cx("grid grid-cols-[minmax(20rem,0.44fr)_minmax(24rem,0.56fr)] items-start gap-[clamp(2rem,6vw,5rem)] py-[clamp(3.5rem,7vw,7rem)] text-[color:var(--color-dark-ink)] max-[860px]:grid-cols-1", fullBleed1180, darkGridBackground),
  contactFormCopy: "sticky top-28 grid content-start gap-0 self-start max-[860px]:static",
  contactDirectActions: "mt-8 flex flex-wrap items-center gap-[0.85rem]",
  contactArchitectureCard: "mt-[clamp(2rem,5vw,3rem)] mb-0 overflow-hidden border border-[var(--color-dark-rule)] bg-[var(--color-dark-panel)]",
  contactForm: "grid gap-4 border border-[var(--color-dark)] bg-[var(--color-bg)] p-[clamp(1rem,2.5vw,1.6rem)] text-[color:var(--color-ink)]",
  contactFormHeading: "mb-2 grid gap-3 [&_h2]:max-w-[16ch] [&_h2]:text-[length:var(--text-h3)] [&_p]:m-0 [&_p]:text-[color:var(--color-muted)] [&_p]:leading-[1.55]",
  fieldGrid: "grid grid-cols-2 gap-4 max-[860px]:grid-cols-1",
  fieldLabel: cx("grid gap-[0.45rem] m-0", "[&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-small)] [&_span]:font-[680] [&_span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_input]:focus-visible:[outline:3px_solid_var(--color-focus)] [&_input]:focus-visible:outline-offset-4 [&_select]:focus-visible:[outline:3px_solid_var(--color-focus)] [&_select]:focus-visible:outline-offset-4 [&_textarea]:focus-visible:[outline:3px_solid_var(--color-focus)] [&_textarea]:focus-visible:outline-offset-4", "[&_input]:w-full [&_input]:border [&_input]:border-[var(--color-rule)] [&_input]:bg-[var(--color-bg)] [&_input]:px-[0.95rem] [&_input]:py-[0.85rem] [&_input]:text-[color:var(--color-ink)] [&_input]:font-[inherit] [&_input]:leading-[var(--leading-body)]", "[&_select]:w-full [&_select]:border [&_select]:border-[var(--color-rule)] [&_select]:bg-[var(--color-bg)] [&_select]:px-[0.95rem] [&_select]:py-[0.85rem] [&_select]:text-[color:var(--color-ink)] [&_select]:font-[inherit] [&_select]:leading-[var(--leading-body)]", "[&_textarea]:min-h-40 [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:border [&_textarea]:border-[var(--color-rule)] [&_textarea]:bg-[var(--color-bg)] [&_textarea]:px-[0.95rem] [&_textarea]:py-[0.85rem] [&_textarea]:text-[color:var(--color-ink)] [&_textarea]:font-[inherit] [&_textarea]:leading-[var(--leading-body)]"),
  contactChoice: cx("grid gap-[0.45rem] m-0 border border-[var(--color-rule)] px-[0.95rem] py-[0.85rem]", "[&_legend]:text-[color:var(--color-muted)] [&_legend]:text-[length:var(--text-small)] [&_legend]:font-[680] [&_legend]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_label]:flex [&_label]:min-h-11 [&_label]:items-center [&_label]:gap-[0.6rem]", "[&_input]:flex-none", "[&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-small)] [&_span]:font-[680] [&_span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]"),
  consentRow: cx("flex min-h-11 items-center gap-[0.6rem] text-[color:var(--color-muted)] text-[length:var(--text-small)] font-[680]", displayFont, "[&_input]:flex-none"),
  contactHoneypot: "absolute size-px overflow-hidden [clip-path:inset(50%)] whitespace-nowrap",
  contactSubmitRow: "mt-8 flex flex-wrap items-center gap-[0.85rem] [&_p]:m-0 [&_p]:text-[color:var(--color-muted)] [&_p]:leading-[1.55] [&_a]:inline-flex [&_a]:min-h-11 [&_a]:items-center",
  contactStatus: cx(displayFont, "m-0 empty:hidden [&:not(:empty)]:border [&:not(:empty)]:border-[var(--color-rule)] [&:not(:empty)]:px-[0.95rem] [&:not(:empty)]:py-[0.85rem] [&:not(:empty)]:text-[length:var(--text-small)] [&:not(:empty)]:font-[520] data-[state=success]:border-[color-mix(in_oklch,var(--color-mint)_55%,var(--color-rule))] data-[state=success]:bg-[color-mix(in_oklch,var(--color-mint)_18%,var(--color-bg))] data-[state=success]:text-[color:var(--color-mint-ink)] data-[state=warning]:border-[color-mix(in_oklch,var(--color-primary)_55%,var(--color-rule))] data-[state=warning]:bg-[color-mix(in_oklch,var(--color-primary)_16%,var(--color-bg))] data-[state=warning]:text-[color:var(--color-primary-ink)] data-[state=error]:border-[color-mix(in_oklch,var(--color-coral)_60%,var(--color-rule))] data-[state=error]:bg-[color-mix(in_oklch,var(--color-coral)_12%,var(--color-bg))] data-[state=error]:text-[color:var(--color-ink)]"),
  architecturePageHero: cx("grid grid-cols-[minmax(0,0.88fr)_minmax(26rem,1.12fr)] items-end gap-[clamp(2rem,6vw,6rem)] min-h-[min(700px,calc(100svh-78px))] border-b border-[var(--color-dark-rule)] py-[clamp(4rem,9vw,7rem)] pb-[clamp(3rem,6vw,5.5rem)] text-[color:var(--color-dark-ink)] max-[860px]:grid-cols-1 max-[860px]:min-h-0", fullBleed1180, darkGridBackground),
  architecturePageCopy: "max-w-[66rem] [&_h1]:max-w-[11ch]",
  architectureHeroAside: "grid gap-4",
  darkPanelFigure: "m-0 overflow-hidden border border-[var(--color-dark-rule)] bg-[var(--color-dark-panel)]",
  sourceIndex: cx("grid gap-4 border-y border-[var(--color-dark)] py-[1.1rem]", "[&_>strong]:text-[length:var(--text-h3)] [&_>strong]:leading-[1.1] [&_>strong]:tracking-normal [&_>strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]"),
  sourceIndexDark: "border-y-[var(--color-dark-rule)]",
  sourceLinks: cx("flex flex-wrap gap-[0.55rem]", "[&_a]:inline-flex [&_a]:min-h-11 [&_a]:items-center [&_a]:border [&_a]:border-[var(--color-rule)] [&_a]:bg-[var(--color-bg)] [&_a]:px-3 [&_a]:py-[0.55rem] [&_a]:text-inherit [&_a]:text-[length:var(--text-small)] [&_a]:font-[680] [&_a]:no-underline [&_a]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]"),
  sourceLinksDark: "[&_a]:border-[var(--color-dark-rule)] [&_a]:bg-[var(--color-dark-mint-panel)] [&_a]:text-[color:var(--color-dark-ink)]",
  sourceLinksInline: "mt-4",
  architectureMap: cx(container, "py-[clamp(2rem,5vw,4.5rem)]"),
  rowList: "grid border-t border-[var(--color-dark)]",
  architectureRow: "grid grid-cols-[minmax(12rem,0.34fr)_minmax(0,1fr)] gap-[clamp(1rem,3vw,3rem)] border-b border-[var(--color-rule)] py-[1.6rem] max-[860px]:grid-cols-1 [&_h3]:text-[length:var(--text-h3)] [&_p]:m-0 [&_p]:max-w-[78ch] [&_p]:text-[color:var(--color-muted)] [&_p]:[text-wrap:pretty]",
  boundaryNote: cx(container, "my-[clamp(1rem,4vw,3rem)] mb-[clamp(4rem,8vw,7rem)] border-y border-[var(--color-dark)] py-[clamp(1.5rem,4vw,3rem)] [&_p]:m-0 [&_p]:max-w-[84ch] [&_p]:text-[color:var(--color-ink)] [&_p]:text-[length:var(--text-lead)] [&_p]:font-[620] [&_p]:leading-[var(--leading-lead)] [&_p]:[text-wrap:pretty] [&_p]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]"),
  caseStudyHero: cx("grid grid-cols-[minmax(0,1fr)_minmax(18rem,0.36fr)] items-end gap-[clamp(2rem,6vw,6rem)] min-h-[min(720px,calc(100svh-78px))] border-b border-[color-mix(in_oklch,var(--color-rule),transparent_18%)] py-[clamp(4rem,9vw,7rem)] pb-[clamp(2.5rem,6vw,5rem)] text-[color:var(--color-ink)] max-[860px]:grid-cols-1 max-[860px]:min-h-0", fullBleed1180, lightGridBackground),
  caseStudyIndexHero: cx("grid grid-cols-[minmax(0,0.8fr)_minmax(24rem,1.2fr)] items-end gap-[clamp(2rem,6vw,6rem)] min-h-[min(640px,calc(100svh-78px))] border-b border-[color-mix(in_oklch,var(--color-rule),transparent_18%)] py-[clamp(4rem,9vw,7rem)] pb-[clamp(3rem,6vw,5.5rem)] text-[color:var(--color-ink)] max-[860px]:grid-cols-1 max-[860px]:min-h-0", fullBleed1180, "[background:radial-gradient(circle_at_18%_26%,color-mix(in_oklch,var(--color-blush),transparent_24%),transparent_24rem),radial-gradient(circle_at_76%_18%,color-mix(in_oklch,var(--color-sky),transparent_24%),transparent_26rem),radial-gradient(circle_at_72%_74%,color-mix(in_oklch,var(--color-mint),transparent_34%),transparent_30rem),linear-gradient(90deg,color-mix(in_oklch,var(--color-ink),transparent_95%)_1px,transparent_1px),linear-gradient(0deg,color-mix(in_oklch,var(--color-ink),transparent_96%)_1px,transparent_1px),var(--color-bg)] bg-[length:auto,auto,auto,4.5rem_4.5rem,4.5rem_4.5rem,auto]"),
  caseStudyHeroCopy: "max-w-[66rem] [&_h1]:max-w-[10ch]",
  caseIndexProofWall: "grid grid-cols-[1.1fr_0.74fr] grid-rows-2 gap-[0.8rem] h-[clamp(24rem,42vw,34rem)] m-0 max-[860px]:grid-cols-2 max-[560px]:grid-cols-1 max-[560px]:h-auto",
  caseIndexProofFrame: "h-full min-h-0 w-full overflow-hidden rounded-md border border-[color-mix(in_oklch,var(--color-rule),var(--color-ink)_8%)] bg-[var(--color-bg)] shadow-[var(--shadow-lifted)] first:row-span-2 max-[860px]:first:row-auto max-[560px]:h-auto max-[560px]:aspect-[1.85]",
  caseStudyStatus: cx("grid gap-3 rounded-lg border border-[color-mix(in_oklch,var(--color-rule),var(--color-ink)_8%)] bg-[color-mix(in_oklch,var(--color-bg),transparent_8%)] p-4 shadow-[var(--shadow-lifted)]", "[&_img]:aspect-[1.75] [&_img]:w-full [&_img]:rounded-md [&_img]:border [&_img]:border-[color-mix(in_oklch,var(--color-rule),transparent_16%)] [&_img]:bg-[var(--color-surface)] [&_img]:object-cover [&_img]:object-[center_34%]", "[&_span]:text-[color:var(--color-coral)] [&_span]:text-[length:var(--text-small)] [&_span]:font-[680] [&_span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_strong]:text-[length:var(--text-h3)] [&_strong]:font-[680] [&_strong]:leading-[1.12] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]"),
  contentSection: cx(container, "py-[clamp(2rem,5vw,4.5rem)]"),
  selectedWorkRow: "grid min-h-[9.5rem] grid-cols-[minmax(8rem,0.16fr)_minmax(12rem,0.24fr)_minmax(10rem,0.2fr)_minmax(0,1fr)_minmax(9rem,0.16fr)] items-center gap-[clamp(1rem,2vw,2rem)] border-b border-[var(--color-rule)] text-inherit no-underline max-[860px]:grid-cols-1 [&>span]:text-[color:var(--color-muted)] [&>span]:text-[length:var(--text-small)] [&>span]:font-[680] [&_em]:not-italic [&_em]:text-[color:var(--color-muted)] [&_em]:text-[length:var(--text-small)] [&_em]:font-[680] [&_p]:m-0 [&_p]:text-[color:var(--color-muted)] [&_p]:leading-[1.55] [&_p]:[text-wrap:pretty]",
  selectedWorkShot: "m-0 aspect-[1.85] overflow-hidden border border-[var(--color-rule)] bg-[var(--color-surface)] max-[560px]:max-w-[32rem] [&>span]:grid [&>span]:h-full [&>span]:w-full [&>span]:place-items-center [&>span]:text-center [&>span]:text-[color:var(--color-muted)] [&>span]:text-[length:var(--text-caption)] [&>span]:font-[680]",
  selectedWorkTitle: cx(displayFont, "text-[1.6rem] font-[680] leading-[1.12]"),
  studyRow: "grid grid-cols-[minmax(12rem,0.34fr)_minmax(0,1fr)] gap-[clamp(1rem,3vw,3rem)] border-b border-[var(--color-rule)] py-[1.6rem] max-[860px]:grid-cols-1 [&_h3]:text-[length:var(--text-h3)] [&_p]:m-0 [&_p]:max-w-[78ch] [&_p]:text-[color:var(--color-muted)] [&_p]:[text-wrap:pretty]",
  evidenceLink: cx("grid min-h-[88px] grid-cols-[minmax(12rem,0.34fr)_minmax(0,1fr)] items-center gap-[clamp(1rem,3vw,3rem)] border-b border-[var(--color-rule)] py-[1.6rem] text-inherit no-underline max-[860px]:grid-cols-1", "[&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-small)] [&_span]:font-[680] [&_span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_strong]:text-[length:var(--text-lead)] [&_strong]:font-[620] [&_strong]:leading-[var(--leading-lead)] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]"),
  confidentiality: cx(container, "my-[clamp(1rem,4vw,3rem)] mb-[clamp(4rem,8vw,7rem)] border-y border-[var(--color-dark)] py-[clamp(1.5rem,4vw,3rem)] [&_h2]:mb-4 [&_h2]:max-w-[18ch] [&_p]:m-0 [&_p]:max-w-[84ch] [&_p]:text-[color:var(--color-muted)] [&_p]:text-[length:var(--text-lead)] [&_p]:leading-[var(--leading-lead)] [&_p]:[text-wrap:pretty]"),
  resumeHero: cx("grid grid-cols-[minmax(22rem,0.46fr)_minmax(34rem,0.54fr)] items-center gap-[clamp(2rem,5vw,5rem)] min-h-[min(780px,calc(100svh-78px))] py-[clamp(3.5rem,7vw,7rem)] text-[color:var(--color-dark-ink)] shadow-[inset_0_-1px_var(--color-dark-rule)] max-[860px]:grid-cols-1 max-[860px]:min-h-0", fullBleed1320, "[background:linear-gradient(90deg,color-mix(in_oklch,var(--color-mint),transparent_91%)_1px,transparent_1px),linear-gradient(0deg,color-mix(in_oklch,var(--color-primary),transparent_93%)_1px,transparent_1px),var(--color-dark)] bg-[length:4.5rem_4.5rem,4.5rem_4.5rem,auto]"),
  resumeIdentity: "max-w-[42rem]",
  resumeRole: cx(displayFont, "m-0 mb-4 text-[color:var(--color-dark-muted)] text-[length:var(--text-h3)] font-[680] leading-[1.12]"),
  resumeProofPanel: "grid min-w-0 content-center gap-4 self-stretch",
  resumeProofCopy: cx("grid gap-[0.65rem] border-y border-[var(--color-dark-rule)] py-4", "[&_span]:text-[color:var(--color-dark-honey)] [&_span]:text-[length:var(--text-small)] [&_span]:font-[680] [&_span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_strong]:max-w-[18ch] [&_strong]:text-[color:var(--color-dark-ink)] [&_strong]:text-[length:var(--text-h3)] [&_strong]:font-[680] [&_strong]:leading-[1.08] [&_strong]:[text-wrap:balance] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_p]:m-0 [&_p]:max-w-[58ch] [&_p]:text-[color:var(--color-dark-muted)] [&_p]:leading-[var(--leading-dark-body)] [&_p]:[text-wrap:pretty]"),
  resumeContact: cx("grid gap-[0.85rem] border-y border-[var(--color-dark-rule)] py-4", "[&_>span]:text-[color:var(--color-dark-muted)] [&_>span]:text-[length:var(--text-small)] [&_>span]:font-[680] [&_>span]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_a]:grid [&_a]:min-h-11 [&_a]:border-t [&_a]:border-[var(--color-dark-rule)] [&_a]:pt-3 [&_a]:text-[color:var(--color-dark-ink)] [&_a]:no-underline", "[&_strong]:text-[color:var(--color-dark-honey)] [&_strong]:text-[length:var(--text-caption)] [&_strong]:font-[680] [&_strong]:[font-family:'Mona_Sans_Variable','Mona_Sans',ui-sans-serif,system-ui,sans-serif]", "[&_a_span]:text-[color:var(--color-dark-muted)] [&_a_span]:[overflow-wrap:anywhere]"),
  resumeCopy: "grid max-w-[86ch] gap-4 border-t border-[var(--color-dark)] pt-[1.4rem] [&_p]:m-0 [&_p]:text-[color:var(--color-muted)] [&_p]:text-[length:var(--text-lead)] [&_p]:leading-[var(--leading-lead)] [&_p]:[text-wrap:pretty]",
  resumeRow: "grid grid-cols-[minmax(10rem,0.28fr)_minmax(0,1fr)] gap-[clamp(1rem,3vw,3rem)] border-b border-[var(--color-rule)] py-[1.35rem] max-[860px]:grid-cols-1 [&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-small)] [&_span]:font-[680] [&_p]:m-0 [&_p]:max-w-[82ch] [&_p]:text-[color:var(--color-muted)] [&_p]:[text-wrap:pretty] [&_strong]:text-[color:var(--color-ink)] [&_strong]:font-[680]",
  resumeEntry: "grid gap-3 border-b border-[var(--color-rule)] py-[1.6rem] [&_h3]:text-[length:var(--text-h3)] [&_p]:m-0 [&_p]:max-w-[86ch] [&_p]:text-[color:var(--color-muted)] [&_p]:[text-wrap:pretty] [&_ul]:m-0 [&_ul]:grid [&_ul]:max-w-[86ch] [&_ul]:gap-[0.45rem] [&_ul]:pl-5 [&_ul]:text-[color:var(--color-muted)] [&_ul]:[text-wrap:pretty]",
  resumeEntryHeading: "grid grid-cols-[minmax(0,1fr)_auto] items-baseline gap-4 max-[860px]:grid-cols-1 [&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-small)] [&_span]:font-[680]",
  routeHero: cx(container, "grid grid-cols-[minmax(0,0.92fr)_minmax(17rem,0.34fr)] items-end gap-[clamp(2rem,7vw,7rem)] min-h-[min(680px,calc(100svh-78px))] py-[clamp(4rem,10vw,8rem)] pb-[clamp(2.5rem,6vw,5rem)] max-[860px]:grid-cols-1 max-[860px]:min-h-0"),
  routeHeroCopy: "max-w-[58rem] [&_h1]:max-w-[12ch]",
  routePanel: cx("grid gap-[0.45rem] border-y border-[var(--color-dark)] py-4", displayFont, "[&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-caption)] [&_span]:font-[650]", "[&_strong]:mb-[0.65rem] [&_strong]:text-[1.12rem] [&_strong]:leading-[1.2] [&_strong]:[overflow-wrap:anywhere]"),
  routeProofSection: cx(container, "py-[clamp(2rem,6vw,5rem)] pb-[clamp(4rem,9vw,7.5rem)]"),
  routeProofItem: "grid grid-cols-[minmax(8rem,0.28fr)_minmax(0,1fr)] gap-5 border-b border-[var(--color-rule)] py-[1.35rem] max-[860px]:grid-cols-1 [&_span]:text-[color:var(--color-muted)] [&_span]:text-[length:var(--text-caption)] [&_span]:font-[650] [&_p]:m-0 [&_p]:max-w-[68ch] [&_p]:text-[color:var(--color-muted)] [&_p]:[text-wrap:pretty]",
  privacyBoundaryNote: cx(displayFont, "mt-[clamp(1rem,3vw,2rem)] mb-0 max-w-[84ch] border-t border-[var(--color-rule)] pt-4 text-[color:var(--color-ink)] text-[length:var(--text-lead)] font-[620] leading-[var(--leading-lead)] [text-wrap:pretty]"),
} as const;

export function proofImageClass(kind = "site") {
  return cx(
    ui.proofImage,
    kind === "landing" && "object-top [transform:scale(1.08)] [transform-origin:50%_8%]",
    kind === "dashboard" && "object-left-top [transform:scale(1.32)] [transform-origin:18%_8%]",
  );
}

export function screenshotImageClass(kind = "site", scale: "normal" | "compact" = "normal") {
  return cx(
    "block h-full w-full object-cover object-[center_34%] [filter:saturate(1.05)_contrast(1.04)]",
    kind === "landing" && "object-[center_18%] [transform:scale(1.08)] [transform-origin:50%_12%]",
    kind === "dashboard" && (scale === "compact"
      ? "object-left-top [transform:scale(1.28)] [transform-origin:16%_8%]"
      : "object-left-top [transform:scale(1.3)] [transform-origin:16%_8%]"),
    kind === "diagram" && "object-center [transform:scale(1.02)]",
  );
}
