import { cn } from "@/lib/utils";

export { cn };

export const dashboardThemeVars = cn(
  "[--background:oklch(0.978_0.006_235)] [--foreground:oklch(0.17_0.035_242)]",
  "[--card:oklch(1_0_0)] [--card-foreground:oklch(0.17_0.035_242)]",
  "[--popover:oklch(1_0_0)] [--popover-foreground:oklch(0.17_0.035_242)]",
  "[--primary:oklch(0.44_0.13_170)] [--primary-foreground:oklch(0.99_0.01_170)]",
  "[--secondary:oklch(0.93_0.025_205)] [--secondary-foreground:oklch(0.22_0.055_232)]",
  "[--muted:oklch(0.94_0.01_232)] [--muted-foreground:oklch(0.38_0.038_238)]",
  "[--accent:oklch(0.78_0.14_78)] [--accent-foreground:oklch(0.19_0.045_68)]",
  "[--destructive:oklch(0.58_0.2_28)] [--border:oklch(0.84_0.012_235)]",
  "[--input:oklch(0.84_0.012_235)] [--ring:oklch(0.48_0.12_170)]",
  "[--chart-1:oklch(0.58_0.12_174)] [--chart-2:oklch(0.78_0.15_78)]",
  "[--chart-3:oklch(0.68_0.15_24)] [--chart-4:oklch(0.58_0.12_252)]",
  "[--chart-5:oklch(0.7_0.1_326)] [--radius:0.625rem]",
  "[--sidebar:oklch(0.18_0.052_236)] [--sidebar-foreground:oklch(0.96_0.012_218)]",
  "[--sidebar-primary:oklch(0.77_0.14_79)] [--sidebar-primary-foreground:oklch(0.17_0.048_236)]",
  "[--sidebar-accent:oklch(0.26_0.07_234)] [--sidebar-accent-foreground:oklch(0.985_0.01_218)]",
  "[--sidebar-border:oklch(0.31_0.055_234)] [--sidebar-ring:oklch(0.77_0.14_79)]",
);

export const dashboardClass = {
  appRoot: cn(dashboardThemeVars, "min-h-screen min-w-80 bg-background text-foreground font-sans"),
  workspace: "flex flex-col gap-7",
  pageHeading: cn(
    "flex max-w-3xl flex-col gap-3",
    "[&_h1]:text-3xl [&_h1]:font-semibold [&_h1]:leading-tight [&_h1]:tracking-normal [&_h1]:text-foreground sm:[&_h1]:text-4xl",
    "[&_p]:mt-2 [&_p]:max-w-3xl [&_p]:text-base [&_p]:leading-7 [&_p]:text-muted-foreground",
  ),
  pageHeadingWithAction: "max-w-none flex-row flex-wrap items-end justify-between gap-4",
  pageHeadingMain: "flex max-w-3xl flex-col gap-3",
  pageHeadingAction: "shrink-0 pb-1",
  statusAlert: "sticky top-4 z-10 max-w-5xl border-primary/30 bg-card shadow-sm",
  cardShadow: "shadow-sm",
  cardHeaderRule: "gap-4 border-b bg-card pb-4",
  projectShell: "!grid gap-6 min-[900px]:grid-cols-[minmax(13rem,16rem)_minmax(0,1fr)] min-[900px]:items-start",
  projectNavPanel: "h-fit min-w-0 min-[900px]:sticky min-[900px]:top-6",
  projectNavHeader: "mb-2 flex items-center justify-between gap-3 px-1",
  projectNavLabel: "text-sm font-semibold text-foreground",
  projectTabsList: cn(
    "!grid h-auto w-full max-w-full min-w-0 grid-cols-[repeat(auto-fit,minmax(15rem,1fr))] items-stretch justify-start gap-1.5 overflow-visible bg-transparent p-0",
    "min-[900px]:!flex min-[900px]:!min-w-0 min-[900px]:!flex-col min-[900px]:gap-1",
  ),
  projectTabTrigger: cn(
    "group/project-tab flex h-auto w-full min-w-0 items-center justify-start gap-3 rounded-lg border border-transparent bg-transparent px-3 py-2.5 text-left text-foreground/80 shadow-none transition-colors duration-150",
    "hover:bg-card/70 hover:text-foreground data-active:border-border data-active:bg-card data-active:text-foreground data-active:shadow-sm motion-reduce:transition-none",
  ),
  projectTabCopy: "min-w-0 flex-1",
  projectTabTitle: "block max-w-full truncate text-sm font-medium group-data-[state=active]/project-tab:font-semibold group-data-[state=active]/project-tab:text-primary",
  projectTabMeta: "mt-0.5 block max-w-full truncate text-xs text-muted-foreground",
  newProjectForm: "!grid gap-4 md:grid-cols-2 xl:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_minmax(0,1fr)_minmax(11rem,13rem)_auto] xl:items-end",
  projectEditorGrid: "grid gap-6 min-[1536px]:grid-cols-[minmax(0,1fr)_minmax(20rem,23rem)] min-[1536px]:items-start",
  projectColumn: "flex min-w-0 flex-col gap-6",
  projectSummaryCard: "gap-4 shadow-sm",
  projectSummaryHeader: "flex-row items-start justify-between gap-4 max-[640px]:!flex max-[640px]:flex-col max-[640px]:items-start",
  projectSummaryTitle: "text-xl leading-tight",
  projectSummaryPaths: "mt-1 break-words",
  projectSummaryBadges: "flex max-w-56 flex-wrap justify-end gap-1.5 max-[640px]:max-w-none max-[640px]:justify-start",
  projectSummaryContent: "flex flex-col gap-4",
  projectSummaryUrl: "inline-flex w-fit max-w-full items-center gap-1 truncate text-sm font-medium text-primary underline-offset-4 hover:underline",
  projectSummaryUrlEmpty: "text-muted-foreground no-underline",
  publishBar: "flex flex-col gap-3 border-t pt-4 sm:flex-row sm:items-center sm:justify-between",
  publishMeta: "flex flex-wrap items-center gap-x-5 gap-y-1 text-sm text-muted-foreground tabular-nums",
  localeEditor: "min-w-0 shadow-sm",
  localeHeader: "gap-4 border-b bg-card pb-4",
  localeTabsList: cn(
    "h-auto w-fit !flex-row border bg-muted/40 p-1 shadow-none",
    "[&_[data-slot=tabs-trigger]]:w-auto [&_[data-slot=tabs-trigger]]:justify-center [&_[data-slot=tabs-trigger]]:px-3 [&_[data-slot=tabs-trigger]]:py-1",
  ),
  projectFormHeader: "flex flex-col gap-3 border-b pb-4 sm:flex-row sm:items-start sm:justify-between [&_h2]:text-base [&_h2]:font-semibold [&_h2]:text-foreground [&_p]:mt-1 [&_p]:text-sm [&_p]:text-muted-foreground",
  editForm: "flex flex-col gap-6",
  formGrid2: "grid gap-4 md:grid-cols-2",
  formGrid3: "grid gap-4 md:grid-cols-3",
  formActionRow: "flex flex-col gap-3 border-t bg-muted/30 px-4 py-3 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between",
  mediaList: "flex flex-col gap-3",
  mediaCardHeader: "border-b pb-4",
  mediaRow: "flex items-start gap-3 rounded-lg border p-3 transition-colors duration-150 motion-reduce:transition-none",
  mediaRowSelected: "border-primary/45 bg-primary/5",
  mediaThumb: "aspect-[4/3] w-20 shrink-0 rounded-md border object-cover",
  mediaImageEmpty: "grid shrink-0 place-content-center gap-1 border bg-muted/50 text-center text-muted-foreground [&_small]:px-2 [&_small]:text-xs [&_svg]:mx-auto [&_svg]:size-6",
  mediaSelectedPreview: "max-w-xl overflow-hidden rounded-lg border",
  mediaPreviewFrame: "aspect-video w-full rounded-none border-0 border-b object-cover",
  mediaPreviewCopy: "flex flex-col gap-0.5 p-3 [&_p]:text-sm [&_p]:leading-5 [&_p]:text-muted-foreground [&_span]:text-xs [&_span]:font-semibold [&_span]:text-muted-foreground [&_strong]:break-words [&_strong]:text-sm [&_strong]:font-medium [&_strong]:text-foreground",
  mediaSelectedLabel: "text-primary",
  mediaRowBody: "min-w-0 flex-1",
  mediaRowTitle: "truncate text-sm font-medium text-foreground",
  mediaRowText: "mt-0.5 line-clamp-2 text-sm leading-5 text-muted-foreground",
  mediaRowTags: "mt-2 flex flex-wrap items-center gap-1.5",
  mediaRowActions: "mt-2.5 flex flex-wrap items-center gap-2",
  mediaEmptyNote: "rounded-lg border border-dashed p-4 text-sm leading-6 text-muted-foreground",
  uploadPreview: "overflow-hidden rounded-lg border bg-background [&_figcaption]:truncate [&_figcaption]:border-t [&_figcaption]:px-3 [&_figcaption]:py-2 [&_figcaption]:text-xs [&_figcaption]:text-muted-foreground [&_img]:aspect-video [&_img]:w-full [&_img]:object-cover",
  contactSettingForm: "grid gap-4 lg:grid-cols-[minmax(0,1fr)_auto]",
  resumeToolbar: "mb-5 flex flex-col gap-4 border-b pb-5 xl:flex-row xl:items-center xl:justify-between",
  resumeActions: "border-t-0 p-0 xl:min-w-[32rem]",
  resumeEditorGrid: "grid gap-5",
  arrayRow: "grid gap-3 md:grid-cols-[minmax(0,1fr)_auto]",
  nestedEditorRow: "flex flex-col gap-4 rounded-md border bg-muted/30 p-4",
};
